import type { GeneratorResult, PrintSpec, ValidationResult } from "../types.js";
import { generateComposablePartBrepJs, type ComposablePartGenerateOptions } from "./brepjs.composable.js";

type ValidatePrintSpec = (spec: unknown) => ValidationResult;

// brepjs (https://brepjs.dev) is a BRep CAD library for TypeScript. This
// generator emits a `.brep.ts` module following the brepjs-cad authoring
// convention (a module that default-exports a zero-arg function returning a
// shape) so it can be run and verified with the `brep` CLI from brepjs-cad.
// Like the OpenSCAD/CadQuery generators, this only emits source text: it
// does not install brepjs, initialize a WASM kernel, or execute any geometry.

export function brepjsHeader() {
  return "// Generated by printspec 0.2.0\n// Review generated CAD before manufacturing.\nimport { box, cylinder, shape } from 'brepjs';\n\n";
}

export function brepjsNumber(value: unknown) {
  const n = Number(value);
  return Number.isFinite(n) ? String(n) : "0";
}

export function brepjsComment(text: string) {
  return (
    String(text)
      .split("\n")
      .map((line) => `// ${line.replace(/\r/g, "")}`)
      .join("\n") + "\n"
  );
}

// A shared helper emitted into generated code that needs to cut an array of
// Z-axis through holes out of a base shape, at [{x, y, diameter}, ...].
export function brepjsZHolesHelper() {
  return "function cutZHoles(part, holes, throughHeight) {\n  return holes.reduce(\n    (acc, h) =>\n      shape(acc)\n        .cut(shape(cylinder(h.diameter / 2, throughHeight + 0.2)).translate([h.x, h.y, -0.1]).val)\n        .val,\n    part,\n  );\n}\n\n";
}

function invalid(validatePrintSpec: ValidatePrintSpec, spec: PrintSpec) {
  const r = validatePrintSpec(spec);
  return r.valid
    ? null
    : {
        supported: false,
        code: "",
        message: `Validation failed: ${r.errors.slice(0, 3).join("; ")}`,
        warnings: [],
      };
}

// Several part families' schemas include chamfer/fillet/cornerRadius (and,
// for l_bracket, rib) as optional finishing requests that most generators
// don't implement. Rather than silently drop them, report a warning so
// callers know the request was ignored. Pass cornerRadius: false for the one
// family (rounded_rectangular_plate) that actually implements cornerRadius.
function warnings(a: any, opts: { cornerRadius?: boolean } = {}) {
  const w: string[] = [];
  if (a.chamfer != null) w.push("chamfer requested but not implemented");
  if (a.fillet != null) w.push("fillet requested but not implemented");
  if (a.rib?.enabled) w.push("rib requested but not implemented");
  if (opts.cornerRadius !== false && a.cornerRadius != null)
    w.push("cornerRadius requested but not implemented");
  return w;
}

// l_bracket has two legs on different axes (leg A flat, thin along Z; leg B
// standing up, thin along X), so unlike the single-axis families above, its
// holes/slots must be cut along whichever axis the Hole/Slot specifies.
// axis "z" cuts through leg A at (x, y); axis "x" cuts through leg B, reusing
// x as the position along leg B's length and y as the lateral position
// (matching leg A's convention). axis "y" isn't supported; matching entries
// are skipped and reported as a warning instead of silently misplaced.
function brepjsLBracketCuts(
  holes: any[] = [],
  slots: any[] = [],
  thickness: unknown,
  width: unknown,
) {
  const lines: string[] = [];
  let unsupportedAxis = false;
  const throughDepth = (axis: string) => n(axis === "y" ? width : thickness);
  for (const h of holes) {
    const axis = h.axis ?? "z";
    if (axis !== "z" && axis !== "x") {
      unsupportedAxis = true;
      continue;
    }
    const depth = h.depth === "through" || h.depth == null ? throughDepth(axis) : n(h.depth);
    lines.push(
      axis === "z"
        ? `shape(cylinder(${n(h.diameter)} / 2, ${depth} + 0.2)).translate([${n(h.x)}, ${n(h.y)}, -0.1]).val`
        : `shape(cylinder(${n(h.diameter)} / 2, ${depth} + 0.2)).rotate(90, { axis: [0, 1, 0] }).translate([-0.1, ${n(h.y)}, ${n(h.x)}]).val`,
    );
  }
  for (const s of slots) {
    const axis = s.axis;
    if (axis !== "z" && axis !== "x") {
      unsupportedAxis = true;
      continue;
    }
    const depth = s.depth === "through" || s.depth == null ? throughDepth(axis) : n(s.depth);
    lines.push(
      axis === "z"
        ? `shape(box(${n(s.length)}, ${n(s.width)}, ${depth} + 0.2)).translate([${n(s.x)} - ${n(s.length)} / 2, ${n(s.y)} - ${n(s.width)} / 2, -0.1]).val`
        : `shape(box(${depth} + 0.2, ${n(s.width)}, ${n(s.length)})).translate([-0.1, ${n(s.y)} - ${n(s.width)} / 2, ${n(s.x)} - ${n(s.length)} / 2]).val`,
    );
  }
  return { lines, unsupportedAxis };
}

function n(value: unknown) {
  return brepjsNumber(value);
}
function params(a: any) {
  return brepjsComment(`Parameters: ${JSON.stringify(a)}`);
}
function holesLiteral(hs: any[] = []) {
  return `[${hs.map((h) => `{ x: ${n(h.x)}, y: ${n(h.y)}, diameter: ${n(h.diameter)} }`).join(", ")}]`;
}

export function generateBrepJsWithValidator(
  validatePrintSpec: ValidatePrintSpec,
  spec: PrintSpec,
  options?: ComposablePartGenerateOptions,
): GeneratorResult {
  const bad = invalid(validatePrintSpec, spec);
  if (bad) return bad;
  const p: any = spec.part;
  if (!p)
    return { supported: false, code: "", message: "Only part specs are supported.", warnings: [] };
  const a = p.parameters;

  if (p.type === "composable_part") {
    return generateComposablePartBrepJs(p, options);
  }
  if (options?.isolate != null)
    return {
      supported: false,
      code: "",
      message: `isolate is only supported for composable_part specs, not "${p.type}".`,
      warnings: [],
    };

  if (p.type === "rounded_rectangular_plate") {
    const holes = a.holes ?? [];
    const cutHoles = holes.length
      ? `part = cutZHoles(part, ${holesLiteral(holes)}, thickness);\n`
      : "";
    return {
      supported: true,
      warnings: warnings(a, { cornerRadius: false }),
      code: `${brepjsHeader()}${holes.length ? brepjsZHolesHelper() : ""}const length = ${n(a.length)};\nconst width = ${n(a.width)};\nconst thickness = ${n(a.thickness)};\nconst cornerRadius = ${n(a.cornerRadius)};\n\nlet part = shape(box(length, width, thickness))\n  .translate([-length / 2, -width / 2, 0]).val;\nif (cornerRadius > 0) part = shape(part).fillet((e) => e.inDirection('Z'), cornerRadius).val;\n${cutHoles}\nexport default () => part;\n`,
    };
  }

  if (p.type === "spacer_block") {
    const holes = a.holes ?? [];
    const cutHoles = holes.length
      ? `part = cutZHoles(part, ${holesLiteral(holes)}, height);\n`
      : "";
    return {
      supported: true,
      warnings: warnings(a),
      code: `${brepjsHeader()}${holes.length ? brepjsZHolesHelper() : ""}const length = ${n(a.length)};\nconst width = ${n(a.width)};\nconst height = ${n(a.height)};\n\nlet part = shape(box(length, width, height))\n  .translate([-length / 2, -width / 2, 0]).val;\n${cutHoles}\nexport default () => part;\n`,
    };
  }

  if (p.type === "round_spacer") {
    const w = warnings(a);
    const inner =
      a.innerDiameter != null
        ? `part = shape(part)\n  .cut(shape(cylinder(innerDiameter / 2, height + 0.2)).translate([0, 0, -0.1]).val).val;\n`
        : "";
    return {
      supported: true,
      warnings: w,
      code: `${brepjsHeader()}const outerDiameter = ${n(a.outerDiameter)};\nconst height = ${n(a.height)};${a.innerDiameter != null ? `\nconst innerDiameter = ${n(a.innerDiameter)};` : ""}\n\nlet part = cylinder(outerDiameter / 2, height);\n${inner}\nexport default () => part;\n`,
    };
  }

  if (p.type === "electronics_standoff") {
    const hasBase = a.baseDiameter != null && a.baseHeight != null;
    const build = hasBase
      ? `let part = shape(cylinder(baseDiameter / 2, baseHeight))\n  .fuse(shape(cylinder(outerDiameter / 2, height)).translate([0, 0, baseHeight]).val).val;\n`
      : `let part = cylinder(outerDiameter / 2, height);\n`;
    const totalHeight = hasBase ? "baseHeight + height" : "height";
    return {
      supported: true,
      warnings: warnings(a),
      code: `${brepjsHeader()}const outerDiameter = ${n(a.outerDiameter)};\nconst height = ${n(a.height)};\nconst holeDiameter = ${n(a.holeDiameter)};${hasBase ? `\nconst baseDiameter = ${n(a.baseDiameter)};\nconst baseHeight = ${n(a.baseHeight)};` : ""}\n\n${build}part = shape(part)\n  .cut(shape(cylinder(holeDiameter / 2, ${totalHeight} + 0.2)).translate([0, 0, -0.1]).val).val;\n\nexport default () => part;\n`,
    };
  }

  if (p.type === "cable_comb") {
    const count = Number(a.slotCount ?? 6);
    const sw = Number(a.slotWidth ?? 4);
    const tw = Number(a.toothWidth ?? (Number(a.slotSpacing ?? 6) - sw || 2));
    const sd = Number(a.slotDepth ?? 8);
    const th = Number(a.baseThickness ?? a.thickness ?? 3);
    const len = Number(a.length ?? count * sw + (count + 1) * tw);
    const wid = Number(a.width ?? sd + tw);
    const slots: string[] = [];
    for (let i = 0; i < count; i++) {
      const x = -len / 2 + tw + sw / 2 + i * (sw + tw);
      const y = wid / 2 - sd / 2;
      slots.push(
        `shape(box(${n(sw)}, ${n(sd + 0.2)}, ${n(th + 0.2)}))\n    .translate([${n(x)} - ${n(sw)} / 2, ${n(y)} - ${n(sd + 0.2)} / 2, -0.1]).val`,
      );
    }
    const hd = Number(a.mountHoleDiameter ?? 0);
    let mountHoles = "";
    if (hd > 0) {
      const sp = Number(a.mountHoleSpacing ?? 40);
      mountHoles = `part = cutZHoles(\n  part,\n  [\n    { x: ${n(-sp / 2)}, y: 0, diameter: ${n(hd)} },\n    { x: ${n(sp / 2)}, y: 0, diameter: ${n(hd)} },\n  ],\n  ${n(th)},\n);\n`;
    }
    return {
      supported: true,
      warnings: warnings(a),
      code: `${brepjsHeader()}${hd > 0 ? brepjsZHolesHelper() : ""}${brepjsComment("Part family: cable_comb")}${params(a)}let part = shape(box(${n(len)}, ${n(wid)}, ${n(th)}))\n  .translate([${n(-len / 2)}, ${n(-wid / 2)}, 0]).val;\npart = shape(part).cutAll([\n  ${slots.join(",\n  ")},\n]).val;\n${mountHoles}\nexport default () => part;\n`,
    };
  }

  if (p.type === "cable_clip") {
    const baseLength = Number(a.baseLength ?? 28);
    const width = Number(a.width ?? a.baseWidth ?? 12);
    const thickness = Number(a.thickness ?? a.baseThickness ?? 3);
    const cableDiameter = Number(a.cableDiameter ?? a.clipInnerDiameter ?? 6);
    const clearance = Number(a.clearance ?? 0.5);
    const mountingHoles = a.mountingHoles ?? [];
    const mountHoles = mountingHoles.length
      ? `part = cutZHoles(part, ${holesLiteral(mountingHoles)}, thickness);\n`
      : "";
    return {
      supported: true,
      warnings: ["Cable arch is approximated as a rectangular bridge.", ...warnings(a)],
      code: `${brepjsHeader()}${mountingHoles.length ? brepjsZHolesHelper() : ""}${brepjsComment("Part family: cable_clip")}${params(a)}const baseLength = ${n(baseLength)};\nconst width = ${n(width)};\nconst thickness = ${n(thickness)};\nconst cableDiameter = ${n(cableDiameter)};\nconst clearance = ${n(clearance)};\n\nconst base = shape(box(baseLength, width, thickness))\n  .translate([-baseLength / 2, -width / 2, 0]).val;\nconst bridge = shape(box(baseLength * 0.65, width, thickness))\n  .translate([-baseLength * 0.325, -width / 2, thickness + cableDiameter / 2]).val;\nlet part = shape(base).fuse(bridge).val;\npart = shape(part)\n  .cut(\n    shape(cylinder((cableDiameter + clearance) / 2, width + 0.2))\n      .rotate(-90, { axis: [1, 0, 0] })\n      .translate([0, -width / 2 - 0.1, thickness + cableDiameter / 2]).val,\n  ).val;\n${mountHoles}\nexport default () => part;\n`,
    };
  }

  if (p.type === "wall_mount_bracket") {
    return {
      supported: true,
      warnings: warnings(a),
      code: `${brepjsHeader()}${brepjsComment("Part family: wall_mount_bracket")}${params(a)}const width = ${n(a.width)};\nconst height = ${n(a.height)};\nconst thickness = ${n(a.thickness)};\nconst tabDepth = ${n(a.tabDepth)};\nconst screwHoleDiameter = ${n(a.screwHoleDiameter)};\nconst screwHoleSpacing = ${n(a.screwHoleSpacing)};\n\nconst plate = shape(box(width, thickness, height))\n  .translate([-width / 2, -thickness / 2, 0]).val;\nconst tab = shape(box(width, tabDepth, thickness))\n  .translate([-width / 2, 0, 0]).val;\nlet part = shape(plate).fuse(tab).val;\nconst screwHole = (z) =>\n  shape(cylinder(screwHoleDiameter / 2, thickness + 0.2))\n    .rotate(-90, { axis: [1, 0, 0] })\n    .translate([0, -thickness / 2 - 0.1, z]).val;\npart = shape(part)\n  .cutAll([\n    screwHole(height / 2 - screwHoleSpacing / 2),\n    screwHole(height / 2 + screwHoleSpacing / 2),\n  ]).val;\n\nexport default () => part;\n`,
    };
  }

  if (p.type === "l_bracket") {
    const cuts = brepjsLBracketCuts(a.holes, a.slots, a.thickness, a.width);
    const w = ["Light-duty/non-structural bracket; review before use.", ...warnings(a)];
    if (cuts.unsupportedAxis) w.push("hole/slot with axis 'y' is not implemented for l_bracket");
    const cutAll = cuts.lines.length
      ? `part = shape(part).cutAll([\n  ${cuts.lines.join(",\n  ")},\n]).val;\n`
      : "";
    return {
      supported: true,
      warnings: w,
      code: `${brepjsHeader()}${brepjsComment("Part family: l_bracket")}${params(a)}const legLengthA = ${n(a.legLengthA)};\nconst legLengthB = ${n(a.legLengthB)};\nconst width = ${n(a.width)};\nconst thickness = ${n(a.thickness)};\n\nconst legA = shape(box(legLengthA, width, thickness))\n  .translate([0, -width / 2, 0]).val;\nconst legB = shape(box(thickness, width, legLengthB))\n  .translate([0, -width / 2, 0]).val;\nlet part = shape(legA).fuse(legB).val;\n${cutAll}\nexport default () => part;\n`,
    };
  }

  if (p.type === "drawer_divider") {
    return {
      supported: true,
      warnings: warnings(a),
      code: `${brepjsHeader()}${brepjsComment("Part family: drawer_divider")}${params(a)}const length = ${n(a.length)};\nconst height = ${n(a.height)};\nconst thickness = ${n(a.thickness)};\nconst notchCount = ${n(a.notchCount ?? 0)};\nconst notchWidth = ${n(a.notchWidth)};\nconst notchDepth = ${n(a.notchDepth)};\n\nlet part = shape(box(length, thickness, height))\n  .translate([-length / 2, -thickness / 2, 0]).val;\nconst notches = [];\nfor (let i = 1; i <= notchCount; i++) {\n  const x = -length / 2 + (i * length) / (notchCount + 1);\n  notches.push(\n    shape(box(notchWidth, thickness + 0.2, notchDepth + 0.1))\n      .translate([x - notchWidth / 2, -thickness / 2 - 0.1, height - notchDepth]).val,\n  );\n}\nif (notches.length) part = shape(part).cutAll(notches).val;\n\nexport default () => part;\n`,
    };
  }

  if (p.type === "project_enclosure_tray") {
    return {
      supported: true,
      warnings: warnings(a),
      code: `${brepjsHeader()}${brepjsZHolesHelper()}${brepjsComment("Part family: project_enclosure_tray")}${params(a)}const outerWidth = ${n(a.outerWidth)};\nconst outerDepth = ${n(a.outerDepth)};\nconst wallHeight = ${n(a.wallHeight)};\nconst wallThickness = ${n(a.wallThickness)};\nconst floorThickness = ${n(a.floorThickness)};\nconst mountHoleDiameter = ${n(a.mountHoleDiameter ?? 3)};\nconst mountHoleInset = ${n(a.mountHoleInset ?? 8)};\n\nconst floor = shape(box(outerWidth, outerDepth, floorThickness))\n  .translate([-outerWidth / 2, -outerDepth / 2, 0]).val;\nconst wall = (w, d, x, y) =>\n  shape(box(w, d, wallHeight))\n    .translate([x, y, floorThickness]).val;\nconst front = wall(outerWidth, wallThickness, -outerWidth / 2, -outerDepth / 2);\nconst back = wall(outerWidth, wallThickness, -outerWidth / 2, outerDepth / 2 - wallThickness);\nconst left = wall(wallThickness, outerDepth, -outerWidth / 2, -outerDepth / 2);\nconst right = wall(wallThickness, outerDepth, outerWidth / 2 - wallThickness, -outerDepth / 2);\nlet part = shape(floor).fuse(front).fuse(back).fuse(left).fuse(right).val;\nconst mountHoles = [\n  { x: -outerWidth / 2 + mountHoleInset, y: -outerDepth / 2 + mountHoleInset, diameter: mountHoleDiameter },\n  { x: -outerWidth / 2 + mountHoleInset, y: outerDepth / 2 - mountHoleInset, diameter: mountHoleDiameter },\n  { x: outerWidth / 2 - mountHoleInset, y: -outerDepth / 2 + mountHoleInset, diameter: mountHoleDiameter },\n  { x: outerWidth / 2 - mountHoleInset, y: outerDepth / 2 - mountHoleInset, diameter: mountHoleDiameter },\n];\npart = cutZHoles(part, mountHoles, floorThickness);\n\nexport default () => part;\n`,
    };
  }

  return {
    supported: false,
    code: "",
    message: `Unsupported part family: ${p.type}`,
    warnings: [],
  };
}
