import type {GeneratorResult, PrintSpec, ValidationResult} from '../types.js';

type ValidatePrintSpec = (spec: unknown) => ValidationResult;

const header = '# Generated by printspec 0.1.0\n# Review generated CAD before manufacturing.\nimport cadquery as cq\n\n';

function invalid(validatePrintSpec: ValidatePrintSpec, spec: PrintSpec) {
  const r = validatePrintSpec(spec);
  return r.valid ? null : {supported: false, code: '', message: `Validation failed: ${r.errors.slice(0, 3).join('; ')}`, warnings: []};
}

function warnings(a: any) {
  const w: string[] = [];
  if (a.chamfer != null) w.push('chamfer requested but not implemented');
  if (a.fillet != null) w.push('fillet requested but not implemented');
  return w;
}

function holeLines(hs: any[] = []) {
  return hs.map((h) => `part = part.faces(">Z").workplane().pushPoints([(${h.x}, ${h.y})]).hole(${h.diameter})`).join('\n');
}

export function generateCadQueryWithValidator(validatePrintSpec: ValidatePrintSpec, spec: PrintSpec): GeneratorResult {
  const bad = invalid(validatePrintSpec, spec);
  if (bad) return bad;
  const p: any = spec.part;
  if (!p) return {supported: false, code: '', message: 'Only part specs are supported.', warnings: []};
  const a = p.parameters;
  if (p.type === 'rounded_rectangular_plate') return {supported: true, warnings: [], code: `${header}length = ${a.length}\nwidth = ${a.width}\nheight = ${a.thickness}\ncorner_radius = ${a.cornerRadius}\n\npart = cq.Workplane("XY").rounded_rect(length, width, corner_radius).extrude(height)\n${holeLines(a.holes)}\n`};
  if (p.type === 'spacer_block') return {supported: true, warnings: [], code: `${header}length = ${a.length}\nwidth = ${a.width}\nheight = ${a.height}\n\npart = cq.Workplane("XY").box(length, width, height, centered=(True, True, False))\n${holeLines(a.holes)}\n`};
  if (p.type === 'round_spacer') {
    const w = warnings(a);
    return {supported: true, warnings: w, code: `${header}outer_diameter = ${a.outerDiameter}\nheight = ${a.height}${a.innerDiameter != null ? `\ninner_diameter = ${a.innerDiameter}` : ''}\n\npart = cq.Workplane("XY").circle(outer_diameter / 2).extrude(height)${a.innerDiameter != null ? '\npart = part.faces(">Z").workplane().hole(inner_diameter)' : ''}\n`};
  }
  if (p.type === 'electronics_standoff') {
    const hasBase = a.baseDiameter != null && a.baseHeight != null;
    return {supported: true, warnings: [], code: `${header}outer_diameter = ${a.outerDiameter}\nheight = ${a.height}\nhole_diameter = ${a.holeDiameter}${hasBase ? `\nbase_diameter = ${a.baseDiameter}\nbase_height = ${a.baseHeight}` : ''}\n\n${hasBase ? `base = cq.Workplane("XY").circle(base_diameter / 2).extrude(base_height)\nstandoff = cq.Workplane("XY").workplane(offset=base_height).circle(outer_diameter / 2).extrude(height)\npart = base.union(standoff)` : `part = cq.Workplane("XY").circle(outer_diameter / 2).extrude(height)`}\npart = part.faces(">Z").workplane().hole(hole_diameter)\n`};
  }

  if (p.type === 'cable_comb') {
    const count = Number(a.slotCount ?? 6), sw = Number(a.slotWidth ?? 4), tw = Number(a.toothWidth ?? (Number(a.slotSpacing ?? 6) - sw || 2)), sd = Number(a.slotDepth ?? 8), th = Number(a.baseThickness ?? a.thickness ?? 3), len = Number(a.length ?? count * sw + (count + 1) * tw), wid = Number(a.width ?? sd + tw);
    let code = `${header}# Part family: cable_comb\n# Parameters: ${JSON.stringify(a)}\npart = cq.Workplane("XY").box(${len}, ${wid}, ${th}, centered=(True, True, False))\n`;
    for (let i = 0; i < count; i++) code += `part = part.cut(cq.Workplane("XY").center(${-len/2+tw+sw/2+i*(sw+tw)}, ${wid/2-sd/2}).box(${sw}, ${sd+0.2}, ${th+0.2}, centered=(True, True, False)))\n`;
    const hd = Number(a.mountHoleDiameter ?? 0); if (hd > 0) { const sp = Number(a.mountHoleSpacing ?? 40); code += `part = part.faces(\">Z\").workplane().pushPoints([(${-sp/2}, 0), (${sp/2}, 0)]).hole(${hd})\n`; }
    return {supported: true, warnings: [], code};
  }
  if (p.type === 'cable_clip') return {supported: true, warnings: ['Cable arch is approximated as a rectangular bridge.'], code: `${header}# Part family: cable_clip\n# Parameters: ${JSON.stringify(a)}\nbase = cq.Workplane("XY").box(${a.baseLength ?? 28}, ${a.width ?? a.baseWidth ?? 12}, ${a.thickness ?? a.baseThickness ?? 3}, centered=(True, True, False))\nbridge = cq.Workplane("XY").workplane(offset=${a.thickness ?? a.baseThickness ?? 3}+(${a.cableDiameter ?? a.clipInnerDiameter ?? 6}+${a.clearance ?? 0.5})/2).box(${a.baseLength ?? 28}*0.65, ${a.width ?? a.baseWidth ?? 12}, ${a.thickness ?? a.baseThickness ?? 3}, centered=(True, True, False))\npart = base.union(bridge)\n`};
  if (p.type === 'wall_mount_bracket') return {supported: true, warnings: [], code: `${header}# Part family: wall_mount_bracket\n# Parameters: ${JSON.stringify(a)}\nplate = cq.Workplane("XY").box(${a.width}, ${a.thickness}, ${a.height}, centered=(True, True, False))\ntab = cq.Workplane("XY").center(0, ${a.tabDepth}/2).box(${a.width}, ${a.tabDepth}, ${a.thickness}, centered=(True, True, False))\npart = plate.union(tab)\npart = part.faces("<Y").workplane().pushPoints([(0, ${a.height}/2-${a.screwHoleSpacing}/2), (0, ${a.height}/2+${a.screwHoleSpacing}/2)]).hole(${a.screwHoleDiameter})\n`};
  if (p.type === 'l_bracket') return {supported: true, warnings: ['Light-duty/non-structural bracket; review before use.'], code: `${header}# Part family: l_bracket\n# Parameters: ${JSON.stringify(a)}\nleg_a = cq.Workplane("XY").center(${a.legLengthA}/2-${a.thickness}/2, 0).box(${a.legLengthA}, ${a.width}, ${a.thickness}, centered=(True, True, False))\nleg_b = cq.Workplane("XZ").center(${a.thickness}/2, ${a.legLengthB}/2-${a.thickness}/2).box(${a.thickness}, ${a.width}, ${a.legLengthB}, centered=(True, True, False))\npart = leg_a.union(leg_b)\n`};
  if (p.type === 'drawer_divider') return {supported: true, warnings: [], code: `${header}# Part family: drawer_divider\n# Parameters: ${JSON.stringify(a)}\npart = cq.Workplane("XY").box(${a.length}, ${a.thickness}, ${a.height}, centered=(True, True, False))\nfor i in range(1, int(${a.notchCount ?? 0}) + 1):\n    x = -${a.length}/2 + i * ${a.length} / (int(${a.notchCount ?? 0}) + 1)\n    notch = cq.Workplane("XY").center(x, 0).box(${a.notchWidth}, ${a.thickness}+0.2, ${a.notchDepth}, centered=(True, True, False)).translate((0, 0, ${a.height}-${a.notchDepth}))\n    part = part.cut(notch)\n`};
  if (p.type === 'project_enclosure_tray') return {supported: true, warnings: [], code: `${header}# Part family: project_enclosure_tray\n# Parameters: ${JSON.stringify(a)}\nfloor = cq.Workplane("XY").box(${a.outerWidth}, ${a.outerDepth}, ${a.floorThickness}, centered=(True, True, False))\nfront = cq.Workplane("XY").center(0, -${a.outerDepth}/2+${a.wallThickness}/2).box(${a.outerWidth}, ${a.wallThickness}, ${a.wallHeight}, centered=(True, True, False)).translate((0, 0, ${a.floorThickness}))\nback = cq.Workplane("XY").center(0, ${a.outerDepth}/2-${a.wallThickness}/2).box(${a.outerWidth}, ${a.wallThickness}, ${a.wallHeight}, centered=(True, True, False)).translate((0, 0, ${a.floorThickness}))\nleft = cq.Workplane("XY").center(-${a.outerWidth}/2+${a.wallThickness}/2, 0).box(${a.wallThickness}, ${a.outerDepth}, ${a.wallHeight}, centered=(True, True, False)).translate((0, 0, ${a.floorThickness}))\nright = cq.Workplane("XY").center(${a.outerWidth}/2-${a.wallThickness}/2, 0).box(${a.wallThickness}, ${a.outerDepth}, ${a.wallHeight}, centered=(True, True, False)).translate((0, 0, ${a.floorThickness}))\npart = floor.union(front).union(back).union(left).union(right)\n`};
  return {supported: false, code: '', message: `Unsupported part family: ${p.type}`, warnings: []};
}
