import type { GeneratorResult, PrintSpec, ValidationResult } from "../types.js";

type ValidatePrintSpec = (spec: unknown) => ValidationResult;

const header =
  "// Generated by printspec 0.2.0\n// Review generated CAD before manufacturing.\n\n";

function invalid(validatePrintSpec: ValidatePrintSpec, spec: PrintSpec) {
  const r = validatePrintSpec(spec);
  return r.valid
    ? null
    : {
        supported: false,
        code: "",
        message: `Validation failed: ${r.errors.slice(0, 3).join("; ")}`,
        warnings: [],
      };
}

// Several part families' schemas include chamfer/fillet/cornerRadius (and,
// for l_bracket, rib) as optional finishing requests that most generators
// don't implement. Rather than silently drop them, report a warning so
// callers know the request was ignored. Pass cornerRadius: false for the one
// family (rounded_rectangular_plate) that actually implements cornerRadius,
// and chamfer/fillet: false for a family/case that actually builds them.
function warnings(
  a: any,
  opts: { cornerRadius?: boolean; chamfer?: boolean; fillet?: boolean } = {},
) {
  const w: string[] = [];
  if (opts.chamfer !== false && a.chamfer != null)
    w.push("chamfer requested but not implemented");
  if (opts.fillet !== false && a.fillet != null)
    w.push("fillet requested but not implemented");
  if (a.rib?.enabled) w.push("rib requested but not implemented");
  if (opts.cornerRadius !== false && a.cornerRadius != null)
    w.push("cornerRadius requested but not implemented");
  return w;
}

// A chamfer/fillet request parses to [size, edges] or null. edges is "both"
// (no target), or "top"/"bottom" for those recognized targets; any other target
// returns null (not built), so it still reports the unimplemented-warning.
type Finish = [number, "both" | "top" | "bottom"] | null;
function finish(feature: any, sizeKey: string): Finish {
  if (feature == null) return null;
  const t = feature.target;
  if (t == null) return [feature[sizeKey], "both"];
  if (t === "top" || t === "bottom") return [feature[sizeKey], t];
  return null;
}
function chamferInfo(a: any): Finish {
  return finish(a.chamfer, "distance");
}
// Chamfer takes precedence when both are requested, so callers pass the fillet
// only when no chamfer is applied and the two never fight over the same edges.
function filletInfo(a: any): Finish {
  return finish(a.fillet, "radius");
}

// A chamfered solid of revolution: outer radius r over height h, with the
// requested top/bottom outer edge(s) beveled by chamfer. h lets a stepped part
// reuse this for a sub-cylinder of a different height (e.g. a standoff base).
function chamferSolid(
  fn: number,
  r: string,
  edges: string,
  h = "height",
): string {
  const pts =
    edges === "top"
      ? `[[0, 0], [${r}, 0], [${r}, ${h} - chamfer], [${r} - chamfer, ${h}], [0, ${h}]]`
      : edges === "bottom"
        ? `[[0, 0], [${r} - chamfer, 0], [${r}, chamfer], [${r}, ${h}], [0, ${h}]]`
        : `[[0, 0], [${r} - chamfer, 0], [${r}, chamfer], [${r}, ${h} - chamfer], [${r} - chamfer, ${h}], [0, ${h}]]`;
  return `rotate_extrude($fn = ${fn}) polygon(${pts})`;
}

// A filleted solid of revolution. Arc points are emitted as symbolic OpenSCAD
// (sin/cos at render time) so the TS and Python output stay identical. h is the
// extrusion height expression (see chamferSolid).
function filletSolid(
  fn: number,
  r: string,
  edges: string,
  h = "height",
): string {
  const bottomArc = `[for (i = [0:8]) [${r} - fillet + fillet*sin(i*90/8), fillet - fillet*cos(i*90/8)]]`;
  const topArc = `[for (i = [0:8]) [${r} - fillet + fillet*cos(i*90/8), ${h} - fillet + fillet*sin(i*90/8)]]`;
  const pts =
    edges === "top"
      ? `concat([[0, 0], [${r}, 0]], ${topArc}, [[0, ${h}]])`
      : edges === "bottom"
        ? `concat([[0, 0]], ${bottomArc}, [[${r}, ${h}], [0, ${h}]])`
        : `concat([[0, 0]], ${bottomArc}, ${topArc}, [[0, ${h}]])`;
  return `rotate_extrude($fn = ${fn}) polygon(${pts})`;
}

// A chamfered_box() module: a hull() of inset/full cross-sections that bevels
// the requested top/bottom perimeter edge(s) of a centered box.
// `l`/`w` name the cross-section dimensions (default length/width) so a thin
// box family can reuse this with, e.g., `thickness` for its second dimension.
// `h` is the extrusion-height expression, letting a sub-box of a larger part
// reuse this (e.g. a tray floor of `floor_thickness`).
function chamferedBoxBody(
  edges: string,
  l: string = "length",
  w: string = "width",
  h: string = "height",
): string {
  const inset = `square([${l} - 2*chamfer, ${w} - 2*chamfer], center = true)`;
  const full = `square([${l}, ${w}], center = true)`;
  const parts =
    edges === "top"
      ? [
          `    linear_extrude(${h} - chamfer) ${full};`,
          `    translate([0, 0, ${h} - 0.01]) linear_extrude(0.01) ${inset};`,
        ]
      : edges === "bottom"
        ? [
            `    linear_extrude(0.01) ${inset};`,
            `    translate([0, 0, chamfer]) linear_extrude(${h} - chamfer) ${full};`,
          ]
        : [
            `    linear_extrude(0.01) ${inset};`,
            `    translate([0, 0, chamfer]) linear_extrude(${h} - 2*chamfer) ${full};`,
            `    translate([0, 0, ${h} - 0.01]) linear_extrude(0.01) ${inset};`,
          ];
  return `module chamfered_box() {\n  hull() {\n${parts.join("\n")}\n  }\n}`;
}

// A filleted_box() module: a hull() of thin cross-section slices whose inset
// follows the fillet arc, rounding the requested top/bottom perimeter edge(s).
function filletedBoxBody(
  edges: string,
  l: string = "length",
  w: string = "width",
  h: string = "height",
): string {
  const bottomArc = `    for (i = [0:8]) translate([0, 0, fillet - fillet*cos(i*90/8)]) linear_extrude(0.001) square([${l} - 2*fillet + 2*fillet*sin(i*90/8), ${w} - 2*fillet + 2*fillet*sin(i*90/8)], center = true);`;
  const topArc = `    for (i = [0:8]) translate([0, 0, ${h} - fillet + fillet*sin(i*90/8)]) linear_extrude(0.001) square([${l} - 2*fillet + 2*fillet*cos(i*90/8), ${w} - 2*fillet + 2*fillet*cos(i*90/8)], center = true);`;
  const fullBottom = `    linear_extrude(0.001) square([${l}, ${w}], center = true);`;
  const fullTop = `    translate([0, 0, ${h} - 0.001]) linear_extrude(0.001) square([${l}, ${w}], center = true);`;
  const parts =
    edges === "top"
      ? [fullBottom, topArc]
      : edges === "bottom"
        ? [bottomArc, fullTop]
        : [bottomArc, topArc];
  return `module filleted_box() {\n  hull() {\n${parts.join("\n")}\n  }\n}`;
}

function holes(hs: any[] = []) {
  return hs
    .map(
      (h) =>
        `  translate([${h.x}, ${h.y}, -0.1]) cylinder(h = height + 0.2, d = ${h.diameter}, $fn = 48);`,
    )
    .join("\n");
}

// l_bracket has two legs on different axes (leg A flat, thin along Z; leg B
// standing up, thin along X), so unlike the single-axis families above, its
// holes/slots must be cut along whichever axis the Hole/Slot specifies.
// axis "z" cuts through leg A at (x, y); axis "x" cuts through leg B, reusing
// x as the position along leg B's length and y as the lateral position
// (matching leg A's convention). axis "y" isn't supported; matching entries
// are skipped and reported as a warning instead of silently misplaced.
function lBracketCuts(
  holes: any[] = [],
  slots: any[] = [],
  thickness: number,
  width: number,
) {
  const lines: string[] = [];
  let unsupportedAxis = false;
  const throughDepth = (axis: string) => (axis === "y" ? width : thickness);
  for (const h of holes) {
    const axis = h.axis ?? "z";
    if (axis !== "z" && axis !== "x") {
      unsupportedAxis = true;
      continue;
    }
    const depth =
      h.depth === "through" || h.depth == null ? throughDepth(axis) : h.depth;
    lines.push(
      axis === "z"
        ? `  translate([${h.x}, ${h.y}, -0.1]) cylinder(h = ${depth} + 0.2, d = ${h.diameter}, $fn = 32);`
        : `  translate([-0.1, ${h.y}, ${h.x}]) rotate([0, 90, 0]) cylinder(h = ${depth} + 0.2, d = ${h.diameter}, $fn = 32);`,
    );
  }
  for (const s of slots) {
    const axis = s.axis;
    if (axis !== "z" && axis !== "x") {
      unsupportedAxis = true;
      continue;
    }
    const depth =
      s.depth === "through" || s.depth == null ? throughDepth(axis) : s.depth;
    lines.push(
      axis === "z"
        ? `  translate([${s.x} - ${s.length} / 2, ${s.y} - ${s.width} / 2, -0.1]) cube([${s.length}, ${s.width}, ${depth} + 0.2]);`
        : `  translate([-0.1, ${s.y} - ${s.width} / 2, ${s.x} - ${s.length} / 2]) cube([${depth} + 0.2, ${s.width}, ${s.length}]);`,
    );
  }
  return { code: lines.join("\n"), unsupportedAxis };
}

export function generateOpenScadWithValidator(
  validatePrintSpec: ValidatePrintSpec,
  spec: PrintSpec,
): GeneratorResult {
  const bad = invalid(validatePrintSpec, spec);
  if (bad) return bad;
  const p: any = spec.part;
  if (!p)
    return {
      supported: false,
      code: "",
      message: "Only part specs are supported.",
      warnings: [],
    };
  const a = p.parameters;
  if (p.type === "rounded_rectangular_plate") {
    const ch = chamferInfo(a);
    const fi = ch == null ? filletInfo(a) : null;
    // The plate is a hull() of corner columns; finishing the columns' top/bottom
    // edges finishes the whole plate perimeter uniformly.
    const column =
      ch != null
        ? chamferSolid(32, "corner_radius", ch[1])
        : fi != null
          ? filletSolid(32, "corner_radius", fi[1])
          : `cylinder(h = height, r = corner_radius, $fn = 32)`;
    return {
      supported: true,
      warnings: warnings(a, {
        cornerRadius: false,
        chamfer: ch == null,
        fillet: fi == null,
      }),
      code: `${header}length = ${a.length};\nwidth = ${a.width};\nheight = ${a.thickness};\ncorner_radius = ${a.cornerRadius};${ch != null ? `\nchamfer = ${ch[0]};` : ""}${fi != null ? `\nfillet = ${fi[0]};` : ""}\n\nmodule rounded_plate() {\n  hull() {\n    for (x = [-length/2 + corner_radius, length/2 - corner_radius])\n      for (y = [-width/2 + corner_radius, width/2 - corner_radius])\n        translate([x, y, 0]) ${column};\n  }\n}\n\ndifference() {\n  rounded_plate();\n${holes(a.holes)}\n}\n`,
    };
  }
  if (p.type === "spacer_block") {
    const ch = chamferInfo(a);
    const fi = ch == null ? filletInfo(a) : null;
    const body =
      ch != null
        ? `chamfer = ${ch[0]};\n\n${chamferedBoxBody(ch[1])}\n\ndifference() {\n  chamfered_box();\n${holes(a.holes)}\n}\n`
        : fi != null
          ? `fillet = ${fi[0]};\n\n${filletedBoxBody(fi[1])}\n\ndifference() {\n  filleted_box();\n${holes(a.holes)}\n}\n`
          : `\ndifference() {\n  translate([-length/2, -width/2, 0]) cube([length, width, height]);\n${holes(a.holes)}\n}\n`;
    return {
      supported: true,
      warnings: warnings(a, { chamfer: ch == null, fillet: fi == null }),
      code: `${header}length = ${a.length};\nwidth = ${a.width};\nheight = ${a.height};\n${body}`,
    };
  }
  if (p.type === "round_spacer") {
    const ch = chamferInfo(a);
    const fi = ch == null ? filletInfo(a) : null;
    const inner =
      a.innerDiameter != null
        ? `\n  translate([0, 0, -0.1]) cylinder(h = height + 0.2, d = inner_diameter, $fn = 64);`
        : "";
    const outerSolid =
      ch != null
        ? chamferSolid(64, "outer_diameter/2", ch[1])
        : fi != null
          ? filletSolid(64, "outer_diameter/2", fi[1])
          : `cylinder(h = height, d = outer_diameter, $fn = 64)`;
    return {
      supported: true,
      warnings: warnings(a, { chamfer: ch == null, fillet: fi == null }),
      code: `${header}outer_diameter = ${a.outerDiameter};\nheight = ${a.height};${ch != null ? `\nchamfer = ${ch[0]};` : ""}${fi != null ? `\nfillet = ${fi[0]};` : ""}${a.innerDiameter != null ? `\ninner_diameter = ${a.innerDiameter};` : ""}\n\ndifference() {\n  ${outerSolid};${inner}\n}\n`,
    };
  }
  if (p.type === "electronics_standoff") {
    const hasBase = a.baseDiameter != null && a.baseHeight != null;
    const ch = chamferInfo(a);
    const fi = ch == null ? filletInfo(a) : null;
    const finish = ch != null ? ch : fi;
    const solid = ch != null ? chamferSolid : filletSolid;
    const edges = finish != null ? finish[1] : null;
    let body;
    if (!hasBase) {
      // Plain cylinder + hole: finish the outer top/bottom edges directly.
      body =
        finish != null
          ? `${solid(64, "outer_diameter/2", finish[1])};`
          : `cylinder(h = height, d = outer_diameter, $fn = 64);`;
    } else {
      // Stepped standoff: the exposed edges are the shaft top and the base
      // bottom, so whole-part finishes both; the internal base/shaft joint
      // stays square.
      const shaft =
        edges === "both" || edges === "top"
          ? solid(64, "outer_diameter/2", "top")
          : `cylinder(h = height, d = outer_diameter, $fn = 64)`;
      const base =
        edges === "both" || edges === "bottom"
          ? solid(64, "base_diameter/2", "bottom", "base_height")
          : `cylinder(h = base_height, d = base_diameter, $fn = 64)`;
      body = `union() {\n    ${base};\n    translate([0, 0, base_height]) ${shaft};\n  }`;
    }
    return {
      supported: true,
      warnings: warnings(a, { chamfer: ch == null, fillet: fi == null }),
      code: `${header}outer_diameter = ${a.outerDiameter};\nheight = ${a.height};\nhole_diameter = ${a.holeDiameter};${hasBase ? `\nbase_diameter = ${a.baseDiameter};\nbase_height = ${a.baseHeight};` : ""}${ch != null ? `\nchamfer = ${ch[0]};` : ""}${fi != null ? `\nfillet = ${fi[0]};` : ""}\n\ndifference() {\n  ${body}\n  translate([0, 0, -0.1]) cylinder(h = ${hasBase ? "base_height + height" : "height"} + 0.2, d = hole_diameter, $fn = 64);\n}\n`,
    };
  }

  if (p.type === "cable_comb") {
    const count = Number(a.slotCount ?? 6),
      sw = Number(a.slotWidth ?? 4),
      tw = Number(a.toothWidth ?? (Number(a.slotSpacing ?? 6) - sw || 2)),
      sd = Number(a.slotDepth ?? 8),
      th = Number(a.baseThickness ?? a.thickness ?? 3),
      len = Number(a.length ?? count * sw + (count + 1) * tw),
      wid = Number(a.width ?? sd + tw);
    let cuts = "";
    for (let i = 0; i < count; i++)
      cuts += `  translate([${-len / 2 + tw + i * (sw + tw)}, ${wid / 2 - sd}, -0.1]) cube([${sw}, ${sd + 0.2}, ${th + 0.2}]);\n`;
    const hd = Number(a.mountHoleDiameter ?? 0);
    if (hd > 0) {
      const sp = Number(a.mountHoleSpacing ?? 40);
      cuts += `  translate([${-sp / 2}, 0, -0.1]) cylinder(h = ${th + 0.2}, d = ${hd}, $fn = 32);\n  translate([${sp / 2}, 0, -0.1]) cylinder(h = ${th + 0.2}, d = ${hd}, $fn = 32);\n`;
    }
    // A comb is a flat plate (length x width x thickness) with slots cut into
    // one long edge, so its top/bottom flat-face perimeter finishes via the
    // box-body helpers with the slots subtracted from the finished plate.
    const ch = chamferInfo(a);
    const fi = ch == null ? filletInfo(a) : null;
    const boxVars = `length = ${len}; width = ${wid}; height = ${th};\n`;
    const prelude =
      ch != null
        ? `${boxVars}chamfer = ${ch[0]};\n\n${chamferedBoxBody(ch[1])}\n\n`
        : fi != null
          ? `${boxVars}fillet = ${fi[0]};\n\n${filletedBoxBody(fi[1])}\n\n`
          : "";
    const panel =
      ch != null
        ? "  chamfered_box();"
        : fi != null
          ? "  filleted_box();"
          : `  translate([${-len / 2}, ${-wid / 2}, 0]) cube([${len}, ${wid}, ${th}]);`;
    return {
      supported: true,
      warnings: warnings(a, { chamfer: ch == null, fillet: fi == null }),
      code: `${header}// Part family: cable_comb\n// Parameters: ${JSON.stringify(a)}\n\n${prelude}difference() {\n${panel}\n${cuts}}\n`,
    };
  }
  if (p.type === "cable_clip") {
    const mountHoles = (a.mountingHoles ?? [])
      .map(
        (h: any) =>
          `  translate([${h.x}, ${h.y}, -0.1]) cylinder(h = thickness + 0.2, d = ${h.diameter}, $fn = 32);`,
      )
      .join("\n");
    // The clip is a base plate (base_length x width x thickness) with a cable
    // arch bridged over it, so the base plate's bottom outer edge is its one
    // closed, solid perimeter clear of the arch. Only a `bottom` target builds:
    // the base cube becomes a bottom-finished box body (height = thickness),
    // leaving the bridge, cable channel and mount holes unchanged. Whole-part
    // and `top` requests still warn.
    const ch = chamferInfo(a);
    const fi = ch == null ? filletInfo(a) : null;
    const chB = ch != null && ch[1] === "bottom" ? ch : null;
    const fiB = fi != null && fi[1] === "bottom" ? fi : null;
    const prelude =
      chB != null
        ? `chamfer = ${chB[0]};\n\n${chamferedBoxBody("bottom", "base_length", "width", "thickness")}\n\n`
        : fiB != null
          ? `fillet = ${fiB[0]};\n\n${filletedBoxBody("bottom", "base_length", "width", "thickness")}\n\n`
          : "";
    const base =
      chB != null
        ? "    chamfered_box();"
        : fiB != null
          ? "    filleted_box();"
          : "    translate([-base_length/2, -width/2, 0]) cube([base_length, width, thickness]);";
    return {
      supported: true,
      warnings: [
        "Cable arch is approximated as a rectangular bridge.",
        ...warnings(a, { chamfer: chB == null, fillet: fiB == null }),
      ],
      code: `${header}// Part family: cable_clip\n// Parameters: ${JSON.stringify(a)}\n\nbase_length = ${a.baseLength ?? 28};\nwidth = ${a.width ?? a.baseWidth ?? 12};\nthickness = ${a.thickness ?? a.baseThickness ?? 3};\ncable_diameter = ${a.cableDiameter ?? a.clipInnerDiameter ?? 6};\n${prelude}difference() {\n  union() {\n${base}\n    translate([-base_length*0.325, -width/2, thickness + cable_diameter/2]) cube([base_length*0.65, width, thickness]);\n  }\n  translate([0, -width/2 - 0.1, thickness + cable_diameter/2]) rotate([-90,0,0]) cylinder(h = width + 0.2, d = cable_diameter + ${a.clearance ?? 0.5}, $fn = 48);\n${mountHoles}\n}\n`,
    };
  }
  if (p.type === "wall_mount_bracket") {
    // The bracket is a vertical back plate (width x thickness x height) with a
    // horizontal foot tab at its base, so the plate's top edge is its one
    // closed, solid perimeter away from the tab. Only a `top` target builds:
    // the plate cube becomes a top-finished box body (cross-section
    // width x thickness), leaving the tab and screw holes unchanged.
    // Whole-part and `bottom` requests still warn.
    const ch = chamferInfo(a);
    const fi = ch == null ? filletInfo(a) : null;
    const chT = ch != null && ch[1] === "top" ? ch : null;
    const fiT = fi != null && fi[1] === "top" ? fi : null;
    const prelude =
      chT != null
        ? `chamfer = ${chT[0]};\n\n${chamferedBoxBody("top", "width", "thickness")}\n\n`
        : fiT != null
          ? `fillet = ${fiT[0]};\n\n${filletedBoxBody("top", "width", "thickness")}\n\n`
          : "";
    const plate =
      chT != null
        ? "    chamfered_box();"
        : fiT != null
          ? "    filleted_box();"
          : "    translate([-width/2, -thickness/2, 0]) cube([width, thickness, height]);";
    return {
      supported: true,
      warnings: warnings(a, { chamfer: chT == null, fillet: fiT == null }),
      code: `${header}// Part family: wall_mount_bracket\n// Parameters: ${JSON.stringify(a)}\n\nwidth = ${a.width}; height = ${a.height}; thickness = ${a.thickness}; tab_depth = ${a.tabDepth}; screw_hole_diameter = ${a.screwHoleDiameter}; screw_hole_spacing = ${a.screwHoleSpacing};\n${prelude}difference() {\n  union() {\n${plate}\n    translate([-width/2, 0, 0]) cube([width, tab_depth, thickness]);\n  }\n  for (z = [height/2 - screw_hole_spacing/2, height/2 + screw_hole_spacing/2]) translate([0, -thickness/2 - 0.1, z]) rotate([-90,0,0]) cylinder(h = thickness + 0.2, d = screw_hole_diameter, $fn = 32);\n}\n`,
    };
  }
  if (p.type === "l_bracket") {
    const cuts = lBracketCuts(a.holes, a.slots, a.thickness, a.width);
    const w = [
      "Light-duty/non-structural bracket; review before use.",
      ...warnings(a),
    ];
    if (cuts.unsupportedAxis)
      w.push("hole/slot with axis 'y' is not implemented for l_bracket");
    return {
      supported: true,
      warnings: w,
      code: `${header}// Part family: l_bracket\n// Parameters: ${JSON.stringify(a)}\n\nleg_a = ${a.legLengthA}; leg_b = ${a.legLengthB}; width = ${a.width}; thickness = ${a.thickness};\ndifference() {\n  union() {\n    translate([0, -width/2, 0]) cube([leg_a, width, thickness]);\n    translate([0, -width/2, 0]) cube([thickness, width, leg_b]);\n  }\n${cuts.code}\n}\n`,
    };
  }
  if (p.type === "drawer_divider") {
    // A divider is a thin box (length x thickness x height) with notches cut
    // from the top, so its top/bottom perimeter edges can be finished by
    // reusing the box-body helpers (with thickness as the cross-section width)
    // and subtracting the notches from the finished box.
    const ch = chamferInfo(a);
    const fi = ch == null ? filletInfo(a) : null;
    const moduleBlock =
      ch != null
        ? `chamfer = ${ch[0]};\n\n${chamferedBoxBody(ch[1], "length", "thickness")}\n\n`
        : fi != null
          ? `fillet = ${fi[0]};\n\n${filletedBoxBody(fi[1], "length", "thickness")}\n\n`
          : "";
    const panel =
      ch != null
        ? "  chamfered_box();"
        : fi != null
          ? "  filleted_box();"
          : "  translate([-length/2, -thickness/2, 0]) cube([length, thickness, height]);";
    const varsLine = `length = ${a.length}; height = ${a.height}; thickness = ${a.thickness}; notch_count = ${a.notchCount ?? 0}; notch_width = ${a.notchWidth}; notch_depth = ${a.notchDepth};`;
    const notches = `  for (i = [1:notch_count]) translate([-length/2 + i * length / (notch_count + 1) - notch_width/2, -thickness/2 - 0.1, height - notch_depth]) cube([notch_width, thickness + 0.2, notch_depth + 0.1]);`;
    return {
      supported: true,
      warnings: warnings(a, { chamfer: ch == null, fillet: fi == null }),
      code: `${header}// Part family: drawer_divider\n// Parameters: ${JSON.stringify(a)}\n\n${varsLine}\n${moduleBlock}difference() {\n${panel}\n${notches}\n}\n`,
    };
  }
  if (p.type === "project_enclosure_tray") {
    // Only the floor's bottom outer edge is a solid, closed perimeter on a tray
    // (the top is an open wall rim, not a face), so only a `bottom` target is
    // built: the floor cube is swapped for a box-body finished on its bottom
    // edge (height = floor_thickness), leaving the walls and mount holes
    // unchanged. Whole-part and `top` requests still warn.
    const ch = chamferInfo(a);
    const fi = ch == null ? filletInfo(a) : null;
    const chB = ch != null && ch[1] === "bottom" ? ch : null;
    const fiB = fi != null && fi[1] === "bottom" ? fi : null;
    const prelude =
      chB != null
        ? `chamfer = ${chB[0]};\n\n${chamferedBoxBody("bottom", "outer_width", "outer_depth", "floor_thickness")}\n\n`
        : fiB != null
          ? `fillet = ${fiB[0]};\n\n${filletedBoxBody("bottom", "outer_width", "outer_depth", "floor_thickness")}\n\n`
          : "";
    const floor =
      chB != null
        ? "    chamfered_box();"
        : fiB != null
          ? "    filleted_box();"
          : "    translate([-outer_width/2, -outer_depth/2, 0]) cube([outer_width, outer_depth, floor_thickness]);";
    return {
      supported: true,
      warnings: warnings(a, { chamfer: chB == null, fillet: fiB == null }),
      code: `${header}// Part family: project_enclosure_tray\n// Parameters: ${JSON.stringify(a)}\n\nouter_width = ${a.outerWidth}; outer_depth = ${a.outerDepth}; wall_height = ${a.wallHeight}; wall_thickness = ${a.wallThickness}; floor_thickness = ${a.floorThickness}; mount_hole_diameter = ${a.mountHoleDiameter ?? 3}; mount_hole_inset = ${a.mountHoleInset ?? 8};\n${prelude}difference() {\n  union() {\n${floor}\n    translate([-outer_width/2, -outer_depth/2, floor_thickness]) cube([outer_width, wall_thickness, wall_height]);\n    translate([-outer_width/2, outer_depth/2 - wall_thickness, floor_thickness]) cube([outer_width, wall_thickness, wall_height]);\n    translate([-outer_width/2, -outer_depth/2, floor_thickness]) cube([wall_thickness, outer_depth, wall_height]);\n    translate([outer_width/2 - wall_thickness, -outer_depth/2, floor_thickness]) cube([wall_thickness, outer_depth, wall_height]);\n  }\n  for (x = [-outer_width/2 + mount_hole_inset, outer_width/2 - mount_hole_inset]) for (y = [-outer_depth/2 + mount_hole_inset, outer_depth/2 - mount_hole_inset]) translate([x,y,-0.1]) cylinder(h = floor_thickness + 0.2, d = mount_hole_diameter, $fn = 32);\n}\n`,
    };
  }
  return {
    supported: false,
    code: "",
    message: `Unsupported part family: ${p.type}`,
    warnings: [],
  };
}
