import type { GeneratorResult, PrintSpec, ValidationResult } from "../types.js";

type ValidatePrintSpec = (spec: unknown) => ValidationResult;

const header =
  "// Generated by printspec 0.2.0\n// Review generated CAD before manufacturing.\n\n";

function invalid(validatePrintSpec: ValidatePrintSpec, spec: PrintSpec) {
  const r = validatePrintSpec(spec);
  return r.valid
    ? null
    : {
        supported: false,
        code: "",
        message: `Validation failed: ${r.errors.slice(0, 3).join("; ")}`,
        warnings: [],
      };
}

// Several part families' schemas include chamfer/fillet/cornerRadius (and,
// for l_bracket, rib) as optional finishing requests that most generators
// don't implement. Rather than silently drop them, report a warning so
// callers know the request was ignored. Pass cornerRadius: false for the one
// family (rounded_rectangular_plate) that actually implements cornerRadius,
// and chamfer/fillet: false for a family/case that actually builds them.
function warnings(
  a: any,
  opts: { cornerRadius?: boolean; chamfer?: boolean; fillet?: boolean } = {},
) {
  const w: string[] = [];
  if (opts.chamfer !== false && a.chamfer != null)
    w.push("chamfer requested but not implemented");
  if (opts.fillet !== false && a.fillet != null)
    w.push("fillet requested but not implemented");
  if (a.rib?.enabled) w.push("rib requested but not implemented");
  if (opts.cornerRadius !== false && a.cornerRadius != null)
    w.push("cornerRadius requested but not implemented");
  return w;
}

// Only whole-part chamfers (no target) are built; a targeted chamfer stays an
// unimplemented-warning until per-edge targeting is supported.
function wholePartChamfer(a: any): number | null {
  return a.chamfer != null && a.chamfer.target == null
    ? a.chamfer.distance
    : null;
}

// Only whole-part fillets (no target) are built. Chamfer takes precedence when
// both are requested, so the two never fight over the same edges.
function wholePartFillet(a: any): number | null {
  return a.fillet != null && a.fillet.target == null ? a.fillet.radius : null;
}

function holes(hs: any[] = []) {
  return hs
    .map(
      (h) =>
        `  translate([${h.x}, ${h.y}, -0.1]) cylinder(h = height + 0.2, d = ${h.diameter}, $fn = 48);`,
    )
    .join("\n");
}

// l_bracket has two legs on different axes (leg A flat, thin along Z; leg B
// standing up, thin along X), so unlike the single-axis families above, its
// holes/slots must be cut along whichever axis the Hole/Slot specifies.
// axis "z" cuts through leg A at (x, y); axis "x" cuts through leg B, reusing
// x as the position along leg B's length and y as the lateral position
// (matching leg A's convention). axis "y" isn't supported; matching entries
// are skipped and reported as a warning instead of silently misplaced.
function lBracketCuts(
  holes: any[] = [],
  slots: any[] = [],
  thickness: number,
  width: number,
) {
  const lines: string[] = [];
  let unsupportedAxis = false;
  const throughDepth = (axis: string) => (axis === "y" ? width : thickness);
  for (const h of holes) {
    const axis = h.axis ?? "z";
    if (axis !== "z" && axis !== "x") {
      unsupportedAxis = true;
      continue;
    }
    const depth =
      h.depth === "through" || h.depth == null ? throughDepth(axis) : h.depth;
    lines.push(
      axis === "z"
        ? `  translate([${h.x}, ${h.y}, -0.1]) cylinder(h = ${depth} + 0.2, d = ${h.diameter}, $fn = 32);`
        : `  translate([-0.1, ${h.y}, ${h.x}]) rotate([0, 90, 0]) cylinder(h = ${depth} + 0.2, d = ${h.diameter}, $fn = 32);`,
    );
  }
  for (const s of slots) {
    const axis = s.axis;
    if (axis !== "z" && axis !== "x") {
      unsupportedAxis = true;
      continue;
    }
    const depth =
      s.depth === "through" || s.depth == null ? throughDepth(axis) : s.depth;
    lines.push(
      axis === "z"
        ? `  translate([${s.x} - ${s.length} / 2, ${s.y} - ${s.width} / 2, -0.1]) cube([${s.length}, ${s.width}, ${depth} + 0.2]);`
        : `  translate([-0.1, ${s.y} - ${s.width} / 2, ${s.x} - ${s.length} / 2]) cube([${depth} + 0.2, ${s.width}, ${s.length}]);`,
    );
  }
  return { code: lines.join("\n"), unsupportedAxis };
}

export function generateOpenScadWithValidator(
  validatePrintSpec: ValidatePrintSpec,
  spec: PrintSpec,
): GeneratorResult {
  const bad = invalid(validatePrintSpec, spec);
  if (bad) return bad;
  const p: any = spec.part;
  if (!p)
    return {
      supported: false,
      code: "",
      message: "Only part specs are supported.",
      warnings: [],
    };
  const a = p.parameters;
  if (p.type === "rounded_rectangular_plate") {
    const c = wholePartChamfer(a);
    const f = c == null ? wholePartFillet(a) : null;
    // The plate is a hull() of corner columns; finishing the columns' top/bottom
    // edges finishes the whole plate perimeter uniformly.
    const column =
      c != null
        ? `rotate_extrude($fn = 32) polygon([[0, 0], [corner_radius - chamfer, 0], [corner_radius, chamfer], [corner_radius, height - chamfer], [corner_radius - chamfer, height], [0, height]])`
        : f != null
          ? `rotate_extrude($fn = 32) polygon(concat([[0, 0]], [for (i = [0:8]) [corner_radius - fillet + fillet*sin(i*90/8), fillet - fillet*cos(i*90/8)]], [for (i = [0:8]) [corner_radius - fillet + fillet*cos(i*90/8), height - fillet + fillet*sin(i*90/8)]], [[0, height]]))`
          : `cylinder(h = height, r = corner_radius, $fn = 32)`;
    return {
      supported: true,
      warnings: warnings(a, {
        cornerRadius: false,
        chamfer: c == null,
        fillet: f == null,
      }),
      code: `${header}length = ${a.length};\nwidth = ${a.width};\nheight = ${a.thickness};\ncorner_radius = ${a.cornerRadius};${c != null ? `\nchamfer = ${c};` : ""}${f != null ? `\nfillet = ${f};` : ""}\n\nmodule rounded_plate() {\n  hull() {\n    for (x = [-length/2 + corner_radius, length/2 - corner_radius])\n      for (y = [-width/2 + corner_radius, width/2 - corner_radius])\n        translate([x, y, 0]) ${column};\n  }\n}\n\ndifference() {\n  rounded_plate();\n${holes(a.holes)}\n}\n`,
    };
  }
  if (p.type === "spacer_block") {
    const c = wholePartChamfer(a);
    const body =
      c != null
        ? `chamfer = ${c};\n\nmodule chamfered_box() {\n  hull() {\n    linear_extrude(0.01) square([length - 2*chamfer, width - 2*chamfer], center = true);\n    translate([0, 0, chamfer]) linear_extrude(height - 2*chamfer) square([length, width], center = true);\n    translate([0, 0, height - 0.01]) linear_extrude(0.01) square([length - 2*chamfer, width - 2*chamfer], center = true);\n  }\n}\n\ndifference() {\n  chamfered_box();\n${holes(a.holes)}\n}\n`
        : `\ndifference() {\n  translate([-length/2, -width/2, 0]) cube([length, width, height]);\n${holes(a.holes)}\n}\n`;
    return {
      supported: true,
      warnings: warnings(a, { chamfer: c == null }),
      code: `${header}length = ${a.length};\nwidth = ${a.width};\nheight = ${a.height};\n${body}`,
    };
  }
  if (p.type === "round_spacer") {
    const c = wholePartChamfer(a);
    const f = c == null ? wholePartFillet(a) : null;
    const inner =
      a.innerDiameter != null
        ? `\n  translate([0, 0, -0.1]) cylinder(h = height + 0.2, d = inner_diameter, $fn = 64);`
        : "";
    // The fillet arc points are emitted as symbolic OpenSCAD (sin/cos evaluated
    // at render time) so the TypeScript and Python generators stay identical.
    const outerSolid =
      c != null
        ? `rotate_extrude($fn = 64) polygon([[0, 0], [outer_diameter/2 - chamfer, 0], [outer_diameter/2, chamfer], [outer_diameter/2, height - chamfer], [outer_diameter/2 - chamfer, height], [0, height]])`
        : f != null
          ? `rotate_extrude($fn = 64) polygon(concat([[0, 0]], [for (i = [0:8]) [outer_diameter/2 - fillet + fillet*sin(i*90/8), fillet - fillet*cos(i*90/8)]], [for (i = [0:8]) [outer_diameter/2 - fillet + fillet*cos(i*90/8), height - fillet + fillet*sin(i*90/8)]], [[0, height]]))`
          : `cylinder(h = height, d = outer_diameter, $fn = 64)`;
    return {
      supported: true,
      warnings: warnings(a, { chamfer: c == null, fillet: f == null }),
      code: `${header}outer_diameter = ${a.outerDiameter};\nheight = ${a.height};${c != null ? `\nchamfer = ${c};` : ""}${f != null ? `\nfillet = ${f};` : ""}${a.innerDiameter != null ? `\ninner_diameter = ${a.innerDiameter};` : ""}\n\ndifference() {\n  ${outerSolid};${inner}\n}\n`,
    };
  }
  if (p.type === "electronics_standoff") {
    const hasBase = a.baseDiameter != null && a.baseHeight != null;
    return {
      supported: true,
      warnings: warnings(a),
      code: `${header}outer_diameter = ${a.outerDiameter};\nheight = ${a.height};\nhole_diameter = ${a.holeDiameter};${hasBase ? `\nbase_diameter = ${a.baseDiameter};\nbase_height = ${a.baseHeight};` : ""}\n\ndifference() {\n  ${hasBase ? `union() {\n    cylinder(h = base_height, d = base_diameter, $fn = 64);\n    translate([0, 0, base_height]) cylinder(h = height, d = outer_diameter, $fn = 64);\n  }` : `cylinder(h = height, d = outer_diameter, $fn = 64);`}\n  translate([0, 0, -0.1]) cylinder(h = ${hasBase ? "base_height + height" : "height"} + 0.2, d = hole_diameter, $fn = 64);\n}\n`,
    };
  }

  if (p.type === "cable_comb") {
    const count = Number(a.slotCount ?? 6),
      sw = Number(a.slotWidth ?? 4),
      tw = Number(a.toothWidth ?? (Number(a.slotSpacing ?? 6) - sw || 2)),
      sd = Number(a.slotDepth ?? 8),
      th = Number(a.baseThickness ?? a.thickness ?? 3),
      len = Number(a.length ?? count * sw + (count + 1) * tw),
      wid = Number(a.width ?? sd + tw);
    let cuts = "";
    for (let i = 0; i < count; i++)
      cuts += `  translate([${-len / 2 + tw + i * (sw + tw)}, ${wid / 2 - sd}, -0.1]) cube([${sw}, ${sd + 0.2}, ${th + 0.2}]);\n`;
    const hd = Number(a.mountHoleDiameter ?? 0);
    if (hd > 0) {
      const sp = Number(a.mountHoleSpacing ?? 40);
      cuts += `  translate([${-sp / 2}, 0, -0.1]) cylinder(h = ${th + 0.2}, d = ${hd}, $fn = 32);\n  translate([${sp / 2}, 0, -0.1]) cylinder(h = ${th + 0.2}, d = ${hd}, $fn = 32);\n`;
    }
    return {
      supported: true,
      warnings: warnings(a),
      code: `${header}// Part family: cable_comb\n// Parameters: ${JSON.stringify(a)}\n\ndifference() {\n  translate([${-len / 2}, ${-wid / 2}, 0]) cube([${len}, ${wid}, ${th}]);\n${cuts}}\n`,
    };
  }
  if (p.type === "cable_clip") {
    const mountHoles = (a.mountingHoles ?? [])
      .map(
        (h: any) =>
          `  translate([${h.x}, ${h.y}, -0.1]) cylinder(h = thickness + 0.2, d = ${h.diameter}, $fn = 32);`,
      )
      .join("\n");
    return {
      supported: true,
      warnings: [
        "Cable arch is approximated as a rectangular bridge.",
        ...warnings(a),
      ],
      code: `${header}// Part family: cable_clip\n// Parameters: ${JSON.stringify(a)}\n\nbase_length = ${a.baseLength ?? 28};\nwidth = ${a.width ?? a.baseWidth ?? 12};\nthickness = ${a.thickness ?? a.baseThickness ?? 3};\ncable_diameter = ${a.cableDiameter ?? a.clipInnerDiameter ?? 6};\ndifference() {\n  union() {\n    translate([-base_length/2, -width/2, 0]) cube([base_length, width, thickness]);\n    translate([-base_length*0.325, -width/2, thickness + cable_diameter/2]) cube([base_length*0.65, width, thickness]);\n  }\n  translate([0, -width/2 - 0.1, thickness + cable_diameter/2]) rotate([-90,0,0]) cylinder(h = width + 0.2, d = cable_diameter + ${a.clearance ?? 0.5}, $fn = 48);\n${mountHoles}\n}\n`,
    };
  }
  if (p.type === "wall_mount_bracket")
    return {
      supported: true,
      warnings: warnings(a),
      code: `${header}// Part family: wall_mount_bracket\n// Parameters: ${JSON.stringify(a)}\n\nwidth = ${a.width}; height = ${a.height}; thickness = ${a.thickness}; tab_depth = ${a.tabDepth}; screw_hole_diameter = ${a.screwHoleDiameter}; screw_hole_spacing = ${a.screwHoleSpacing};\ndifference() {\n  union() {\n    translate([-width/2, -thickness/2, 0]) cube([width, thickness, height]);\n    translate([-width/2, 0, 0]) cube([width, tab_depth, thickness]);\n  }\n  for (z = [height/2 - screw_hole_spacing/2, height/2 + screw_hole_spacing/2]) translate([0, -thickness/2 - 0.1, z]) rotate([-90,0,0]) cylinder(h = thickness + 0.2, d = screw_hole_diameter, $fn = 32);\n}\n`,
    };
  if (p.type === "l_bracket") {
    const cuts = lBracketCuts(a.holes, a.slots, a.thickness, a.width);
    const w = [
      "Light-duty/non-structural bracket; review before use.",
      ...warnings(a),
    ];
    if (cuts.unsupportedAxis)
      w.push("hole/slot with axis 'y' is not implemented for l_bracket");
    return {
      supported: true,
      warnings: w,
      code: `${header}// Part family: l_bracket\n// Parameters: ${JSON.stringify(a)}\n\nleg_a = ${a.legLengthA}; leg_b = ${a.legLengthB}; width = ${a.width}; thickness = ${a.thickness};\ndifference() {\n  union() {\n    translate([0, -width/2, 0]) cube([leg_a, width, thickness]);\n    translate([0, -width/2, 0]) cube([thickness, width, leg_b]);\n  }\n${cuts.code}\n}\n`,
    };
  }
  if (p.type === "drawer_divider")
    return {
      supported: true,
      warnings: warnings(a),
      code: `${header}// Part family: drawer_divider\n// Parameters: ${JSON.stringify(a)}\n\nlength = ${a.length}; height = ${a.height}; thickness = ${a.thickness}; notch_count = ${a.notchCount ?? 0}; notch_width = ${a.notchWidth}; notch_depth = ${a.notchDepth};\ndifference() {\n  translate([-length/2, -thickness/2, 0]) cube([length, thickness, height]);\n  for (i = [1:notch_count]) translate([-length/2 + i * length / (notch_count + 1) - notch_width/2, -thickness/2 - 0.1, height - notch_depth]) cube([notch_width, thickness + 0.2, notch_depth + 0.1]);\n}\n`,
    };
  if (p.type === "project_enclosure_tray")
    return {
      supported: true,
      warnings: warnings(a),
      code: `${header}// Part family: project_enclosure_tray\n// Parameters: ${JSON.stringify(a)}\n\nouter_width = ${a.outerWidth}; outer_depth = ${a.outerDepth}; wall_height = ${a.wallHeight}; wall_thickness = ${a.wallThickness}; floor_thickness = ${a.floorThickness}; mount_hole_diameter = ${a.mountHoleDiameter ?? 3}; mount_hole_inset = ${a.mountHoleInset ?? 8};\ndifference() {\n  union() {\n    translate([-outer_width/2, -outer_depth/2, 0]) cube([outer_width, outer_depth, floor_thickness]);\n    translate([-outer_width/2, -outer_depth/2, floor_thickness]) cube([outer_width, wall_thickness, wall_height]);\n    translate([-outer_width/2, outer_depth/2 - wall_thickness, floor_thickness]) cube([outer_width, wall_thickness, wall_height]);\n    translate([-outer_width/2, -outer_depth/2, floor_thickness]) cube([wall_thickness, outer_depth, wall_height]);\n    translate([outer_width/2 - wall_thickness, -outer_depth/2, floor_thickness]) cube([wall_thickness, outer_depth, wall_height]);\n  }\n  for (x = [-outer_width/2 + mount_hole_inset, outer_width/2 - mount_hole_inset]) for (y = [-outer_depth/2 + mount_hole_inset, outer_depth/2 - mount_hole_inset]) translate([x,y,-0.1]) cylinder(h = floor_thickness + 0.2, d = mount_hole_diameter, $fn = 32);\n}\n`,
    };
  return {
    supported: false,
    code: "",
    message: `Unsupported part family: ${p.type}`,
    warnings: [],
  };
}
