import type {GeneratorResult, PrintSpec, ValidationResult} from '../types.js';

type ValidatePrintSpec = (spec: unknown) => ValidationResult;

const header = '// Generated by printspec 0.1.0\n// Review generated CAD before manufacturing.\n\n';

function invalid(validatePrintSpec: ValidatePrintSpec, spec: PrintSpec) {
  const r = validatePrintSpec(spec);
  return r.valid ? null : {supported: false, code: '', message: `Validation failed: ${r.errors.slice(0, 3).join('; ')}`, warnings: []};
}

function warnings(a: any) {
  const w: string[] = [];
  if (a.chamfer != null) w.push('chamfer requested but not implemented');
  if (a.fillet != null) w.push('fillet requested but not implemented');
  return w;
}

function holes(hs: any[] = []) {
  return hs.map((h) => `  translate([${h.x}, ${h.y}, -0.1]) cylinder(h = height + 0.2, d = ${h.diameter}, $fn = 48);`).join('\n');
}

export function generateOpenScadWithValidator(validatePrintSpec: ValidatePrintSpec, spec: PrintSpec): GeneratorResult {
  const bad = invalid(validatePrintSpec, spec);
  if (bad) return bad;
  const p: any = spec.part;
  if (!p) return {supported: false, code: '', message: 'Only part specs are supported.', warnings: []};
  const a = p.parameters;
  if (p.type === 'rounded_rectangular_plate') return {supported: true, warnings: [], code: `${header}length = ${a.length};\nwidth = ${a.width};\nheight = ${a.thickness};\ncorner_radius = ${a.cornerRadius};\n\nmodule rounded_plate() {\n  hull() {\n    for (x = [-length/2 + corner_radius, length/2 - corner_radius])\n      for (y = [-width/2 + corner_radius, width/2 - corner_radius])\n        translate([x, y, 0]) cylinder(h = height, r = corner_radius, $fn = 32);\n  }\n}\n\ndifference() {\n  rounded_plate();\n${holes(a.holes)}\n}\n`};
  if (p.type === 'spacer_block') return {supported: true, warnings: [], code: `${header}length = ${a.length};\nwidth = ${a.width};\nheight = ${a.height};\n\ndifference() {\n  translate([-length/2, -width/2, 0]) cube([length, width, height]);\n${holes(a.holes)}\n}\n`};
  if (p.type === 'round_spacer') {
    const w = warnings(a);
    const inner = a.innerDiameter != null ? `\n  translate([0, 0, -0.1]) cylinder(h = height + 0.2, d = inner_diameter, $fn = 64);` : '';
    return {supported: true, warnings: w, code: `${header}outer_diameter = ${a.outerDiameter};\nheight = ${a.height};${a.innerDiameter != null ? `\ninner_diameter = ${a.innerDiameter};` : ''}\n\ndifference() {\n  cylinder(h = height, d = outer_diameter, $fn = 64);${inner}\n}\n`};
  }
  if (p.type === 'electronics_standoff') {
    const hasBase = a.baseDiameter != null && a.baseHeight != null;
    return {supported: true, warnings: [], code: `${header}outer_diameter = ${a.outerDiameter};\nheight = ${a.height};\nhole_diameter = ${a.holeDiameter};${hasBase ? `\nbase_diameter = ${a.baseDiameter};\nbase_height = ${a.baseHeight};` : ''}\n\ndifference() {\n  ${hasBase ? `union() {\n    cylinder(h = base_height, d = base_diameter, $fn = 64);\n    translate([0, 0, base_height]) cylinder(h = height, d = outer_diameter, $fn = 64);\n  }` : `cylinder(h = height, d = outer_diameter, $fn = 64);`}\n  translate([0, 0, -0.1]) cylinder(h = ${hasBase ? 'base_height + height' : 'height'} + 0.2, d = hole_diameter, $fn = 64);\n}\n`};
  }

  if (p.type === 'cable_comb') {
    const count = Number(a.slotCount ?? 6), sw = Number(a.slotWidth ?? 4), tw = Number(a.toothWidth ?? (Number(a.slotSpacing ?? 6) - sw || 2)), sd = Number(a.slotDepth ?? 8), th = Number(a.baseThickness ?? a.thickness ?? 3), len = Number(a.length ?? count * sw + (count + 1) * tw), wid = Number(a.width ?? sd + tw);
    let cuts = '';
    for (let i = 0; i < count; i++) cuts += `  translate([${-len / 2 + tw + i * (sw + tw)}, ${wid / 2 - sd}, -0.1]) cube([${sw}, ${sd + 0.2}, ${th + 0.2}]);\n`;
    const hd = Number(a.mountHoleDiameter ?? 0); if (hd > 0) { const sp = Number(a.mountHoleSpacing ?? 40); cuts += `  translate([${-sp/2}, 0, -0.1]) cylinder(h = ${th + 0.2}, d = ${hd}, $fn = 32);\n  translate([${sp/2}, 0, -0.1]) cylinder(h = ${th + 0.2}, d = ${hd}, $fn = 32);\n`; }
    return {supported: true, warnings: [], code: `${header}// Part family: cable_comb\n// Parameters: ${JSON.stringify(a)}\n\ndifference() {\n  translate([${-len/2}, ${-wid/2}, 0]) cube([${len}, ${wid}, ${th}]);\n${cuts}}\n`};
  }
  if (p.type === 'cable_clip') return {supported: true, warnings: ['Cable arch is approximated as a rectangular bridge.'], code: `${header}// Part family: cable_clip\n// Parameters: ${JSON.stringify(a)}\n\nbase_length = ${a.baseLength ?? 28};\nwidth = ${a.width ?? a.baseWidth ?? 12};\nthickness = ${a.thickness ?? a.baseThickness ?? 3};\ncable_diameter = ${a.cableDiameter ?? a.clipInnerDiameter ?? 6};\nmount_hole_diameter = ${a.mountHoleDiameter ?? 0};\ndifference() {\n  union() {\n    translate([-base_length/2, -width/2, 0]) cube([base_length, width, thickness]);\n    translate([-base_length*0.325, -width/2, thickness + cable_diameter/2]) cube([base_length*0.65, width, thickness]);\n  }\n  translate([0, -width/2 - 0.1, thickness + cable_diameter/2]) rotate([-90,0,0]) cylinder(h = width + 0.2, d = cable_diameter + ${a.clearance ?? 0.5}, $fn = 48);\n  if (mount_hole_diameter > 0) translate([-base_length*0.33, 0, -0.1]) cylinder(h = thickness + 0.2, d = mount_hole_diameter, $fn = 32);\n}\n`};
  if (p.type === 'wall_mount_bracket') return {supported: true, warnings: [], code: `${header}// Part family: wall_mount_bracket\n// Parameters: ${JSON.stringify(a)}\n\nwidth = ${a.width}; height = ${a.height}; thickness = ${a.thickness}; tab_depth = ${a.tabDepth}; screw_hole_diameter = ${a.screwHoleDiameter}; screw_hole_spacing = ${a.screwHoleSpacing};\ndifference() {\n  union() {\n    translate([-width/2, -thickness/2, 0]) cube([width, thickness, height]);\n    translate([-width/2, 0, 0]) cube([width, tab_depth, thickness]);\n  }\n  for (z = [height/2 - screw_hole_spacing/2, height/2 + screw_hole_spacing/2]) translate([0, -thickness/2 - 0.1, z]) rotate([-90,0,0]) cylinder(h = thickness + 0.2, d = screw_hole_diameter, $fn = 32);\n}\n`};
  if (p.type === 'l_bracket') return {supported: true, warnings: ['Light-duty/non-structural bracket; review before use.'], code: `${header}// Part family: l_bracket\n// Parameters: ${JSON.stringify(a)}\n\nleg_a = ${a.legLengthA}; leg_b = ${a.legLengthB}; width = ${a.width}; thickness = ${a.thickness}; hole_diameter = ${a.holeDiameter ?? 0}; holes_per_leg = ${a.holesPerLeg ?? 0};\ndifference() {\n  union() {\n    translate([0, -width/2, 0]) cube([leg_a, width, thickness]);\n    translate([0, -width/2, 0]) cube([thickness, width, leg_b]);\n  }\n  for (i = [1:holes_per_leg]) {\n    translate([i * leg_a / (holes_per_leg + 1), 0, -0.1]) cylinder(h = thickness + 0.2, d = hole_diameter, $fn = 32);\n    translate([-0.1, 0, i * leg_b / (holes_per_leg + 1)]) rotate([0,90,0]) cylinder(h = thickness + 0.2, d = hole_diameter, $fn = 32);\n  }\n}\n`};
  if (p.type === 'drawer_divider') return {supported: true, warnings: [], code: `${header}// Part family: drawer_divider\n// Parameters: ${JSON.stringify(a)}\n\nlength = ${a.length}; height = ${a.height}; thickness = ${a.thickness}; notch_count = ${a.notchCount ?? 0}; notch_width = ${a.notchWidth}; notch_depth = ${a.notchDepth};\ndifference() {\n  translate([-length/2, -thickness/2, 0]) cube([length, thickness, height]);\n  for (i = [1:notch_count]) translate([-length/2 + i * length / (notch_count + 1) - notch_width/2, -thickness/2 - 0.1, height - notch_depth]) cube([notch_width, thickness + 0.2, notch_depth + 0.1]);\n}\n`};
  if (p.type === 'project_enclosure_tray') return {supported: true, warnings: [], code: `${header}// Part family: project_enclosure_tray\n// Parameters: ${JSON.stringify(a)}\n\nouter_width = ${a.outerWidth}; outer_depth = ${a.outerDepth}; wall_height = ${a.wallHeight}; wall_thickness = ${a.wallThickness}; floor_thickness = ${a.floorThickness}; mount_hole_diameter = ${a.mountHoleDiameter ?? 3}; mount_hole_inset = ${a.mountHoleInset ?? 8};\ndifference() {\n  union() {\n    translate([-outer_width/2, -outer_depth/2, 0]) cube([outer_width, outer_depth, floor_thickness]);\n    translate([-outer_width/2, -outer_depth/2, floor_thickness]) cube([outer_width, wall_thickness, wall_height]);\n    translate([-outer_width/2, outer_depth/2 - wall_thickness, floor_thickness]) cube([outer_width, wall_thickness, wall_height]);\n    translate([-outer_width/2, -outer_depth/2, floor_thickness]) cube([wall_thickness, outer_depth, wall_height]);\n    translate([outer_width/2 - wall_thickness, -outer_depth/2, floor_thickness]) cube([wall_thickness, outer_depth, wall_height]);\n  }\n  for (x = [-outer_width/2 + mount_hole_inset, outer_width/2 - mount_hole_inset]) for (y = [-outer_depth/2 + mount_hole_inset, outer_depth/2 - mount_hole_inset]) translate([x,y,-0.1]) cylinder(h = floor_thickness + 0.2, d = mount_hole_diameter, $fn = 32);\n}\n`};
  return {supported: false, code: '', message: `Unsupported part family: ${p.type}`, warnings: []};
}
