import {copyFileSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PROJECT_NAME = 'printspec';
const PROJECT_DESCRIPTION = 'JSON Schemas for practical parametric 3D-printable parts.';
const PROJECT_REPO_URL = 'https://github.com/invisra/printspec';
const SOURCE_SCHEMA_DIR = 'schemas';
const PYTHON_SCHEMA_DIR = 'packages/python/printspec/schemas';
const TYPESCRIPT_SCHEMA_DIR = 'packages/typescript/schemas';
const TYPESCRIPT_GENERATED_SCHEMA_MODULE = 'packages/typescript/src/generated/schemas.generated.ts';
const ENABLE_VERCEL_ANALYTICS = process.env.ENABLE_VERCEL_ANALYTICS === '1';

const packageJson = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));
const SCHEMA_VERSION = packageJson.version;
const PUBLIC_PROJECT_DIR = `public/${PROJECT_NAME}`;
const PUBLIC_SCHEMA_DIR = `${PUBLIC_PROJECT_DIR}/${SCHEMA_VERSION}`;
const sourceDir = path.join(root, SOURCE_SCHEMA_DIR);

function readJson(filePath) {
  return JSON.parse(readFileSync(filePath, 'utf8'));
}

function writeJson(filePath, data) {
  writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`);
}


function writeGeneratedTypeScriptSchemas(filePath, schemaEntries) {
  const sorted = [...schemaEntries].sort((a, b) => a.file.localeCompare(b.file));
  const schemaLines = sorted.map(({file, schema}) => `  ${JSON.stringify(file)}: ${JSON.stringify(schema, null, 2).replaceAll('\n', '\n  ')}`).join(',\n');
  const fileList = sorted.map(({file}) => `  ${JSON.stringify(file)}`).join(',\n');
  const content = `// This file is generated by scripts/sync-schemas.mjs.\n// Do not edit manually.\n\nexport const bundledSchemas = {\n${schemaLines}\n} as const;\n\nexport const bundledSchemaFiles = [\n${fileList}\n] as const;\n`;
  mkdirSync(path.dirname(filePath), {recursive: true});
  writeFileSync(filePath, content);
}

function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function schemaSort(a, b) {
  if (a === 'printspec.schema.json') return -1;
  if (b === 'printspec.schema.json') return 1;
  return a.localeCompare(b);
}

function analyticsSnippet() {
  if (!ENABLE_VERCEL_ANALYTICS) return '';
  return `\n<script>\n  window.va =\n    window.va ||\n    function () {\n      (window.vaq = window.vaq || []).push(arguments);\n    };\n</script>\n<script defer src="/_vercel/insights/script.js"></script>`;
}

const BRAND_BASE = 'https://assets.invisra.ai/brand/v1';

function brandHead() {
  return `  <link rel="stylesheet" href="${BRAND_BASE}/brand.min.css">\n  <link rel="icon" href="${BRAND_BASE}/favicon.svg" type="image/svg+xml">\n  <link rel="icon" href="${BRAND_BASE}/favicon-32.png" sizes="32x32" type="image/png">\n  <link rel="icon" href="${BRAND_BASE}/favicon-16.png" sizes="16x16" type="image/png">\n  <link rel="apple-touch-icon" href="${BRAND_BASE}/apple-touch-icon.png">\n  <meta name="theme-color" content="#020617">`;
}

function themeScript() {
  return `<script>
  (function () {
    var key = 'invisra-theme';
    var saved = localStorage.getItem(key);
    var theme = saved === 'light' ? 'light' : 'dark';
    document.documentElement.dataset.theme = theme;

    function updateThemeButton() {
      var button = document.querySelector('[data-theme-toggle]');
      if (button) {
        button.textContent = theme === 'dark' ? 'Light' : 'Dark';
        button.setAttribute('aria-label', 'Switch to ' + (theme === 'dark' ? 'light' : 'dark') + ' theme');
      }
    }

    window.toggleInvisraTheme = function () {
      var current = document.documentElement.dataset.theme === 'light' ? 'light' : 'dark';
      var next = current === 'dark' ? 'light' : 'dark';
      theme = next;
      document.documentElement.dataset.theme = next;
      localStorage.setItem(key, next);
      updateThemeButton();
    };

    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', updateThemeButton);
    } else {
      updateThemeButton();
    }
  })();
</script>`;
}

function logoMarkup() {
  return `<a class="invisra-logo-lockup" href="/${PROJECT_NAME}/" aria-label="printspec home">
      <svg class="invisra-logo-mark invisra-logo-mark-sm" viewBox="0 0 160 380" role="img" aria-hidden="true" focusable="false"><path fill="currentColor" d="M80 6 8 222 38 256 80 356 122 256 152 222Z M80 118 112 214 80 248 48 214Z"></path></svg>
      <span class="invisra-logo-wordmark">Invisra</span>
      <span class="invisra-text-muted">/ printspec</span>
    </a>`;
}

function siteHeader() {
  return `<header class="invisra-header">
  <div class="invisra-container site-nav">
    ${logoMarkup()}
    <nav class="site-links" aria-label="Site navigation">
      <a href="/${PROJECT_NAME}/">Home</a>
      <a href="/${PROJECT_NAME}/validator/">Validator</a>
      <a href="/${PROJECT_NAME}/${SCHEMA_VERSION}/">Schemas</a>
      <a href="https://cad.invisra.ai">PartPilot</a>
      <a href="https://invisra.ai">Invisra</a>
      <button type="button" class="invisra-button invisra-button-ghost theme-toggle" data-theme-toggle onclick="window.toggleInvisraTheme()" aria-label="Switch theme">Light</button>
    </nav>
  </div>
</header>`;
}

function localStyles() {
  return `<style>
    :root{color-scheme:dark light}body.invisra-theme{margin:0;background:radial-gradient(circle at 15% 0%,rgba(59,130,246,.22),transparent 32rem),radial-gradient(circle at 88% 12%,rgba(99,102,241,.18),transparent 30rem),var(--invisra-bg,#020617);color:var(--invisra-text,#e5eefb);font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif}.invisra-header{background:color-mix(in srgb,var(--invisra-bg,#020617),transparent 10%);border-bottom:1px solid var(--invisra-border,rgba(148,163,184,.22));box-shadow:none}.invisra-header::before,.invisra-header::after{display:none;background:transparent;box-shadow:none}html[data-theme=light] .invisra-header{background:rgba(255,255,255,.82);border-bottom-color:rgba(15,23,42,.12);box-shadow:0 1px 0 rgba(255,255,255,.78) inset,0 12px 28px rgba(15,23,42,.06)}html[data-theme=light] body.invisra-theme{background:radial-gradient(circle at 15% 0%,rgba(59,130,246,.12),transparent 32rem),radial-gradient(circle at 88% 12%,rgba(99,102,241,.1),transparent 30rem),var(--invisra-bg,#f8fafc)}html[data-theme=light] .invisra-shell,html[data-theme=light] footer{background:transparent;color:var(--invisra-text,#0f172a)}html[data-theme=light] .invisra-header::before,html[data-theme=light] .invisra-header::after{display:none;background:transparent;box-shadow:none}.site-nav{display:flex;align-items:center;justify-content:space-between;gap:1rem}.site-links{display:flex;align-items:center;gap:.55rem;flex-wrap:wrap}.site-links a,.card-grid .invisra-card>a,.link-row a:not(.invisra-button),.schema h3 a{display:inline-flex;align-items:center;justify-content:center;gap:.35rem;border:1px solid var(--invisra-border,rgba(148,163,184,.24));border-radius:999px;background:color-mix(in srgb,var(--invisra-surface,#0f172a),transparent 28%);box-shadow:0 10px 24px rgba(15,23,42,.08);color:var(--invisra-text,#e5eefb);text-decoration:none;font-weight:800;line-height:1.1;transition:transform .16s ease,border-color .16s ease,background .16s ease,box-shadow .16s ease}.site-links a{padding:.52rem .78rem;font-size:.94rem}.card-grid .invisra-card>a,.link-row a:not(.invisra-button),.schema h3 a{padding:.62rem .9rem}.site-links a:hover,.card-grid .invisra-card>a:hover,.link-row a:not(.invisra-button):hover,.schema h3 a:hover{border-color:color-mix(in srgb,var(--invisra-accent,#38bdf8),transparent 35%);background:color-mix(in srgb,var(--invisra-accent,#38bdf8),transparent 88%);box-shadow:0 14px 30px rgba(14,165,233,.14);transform:translateY(-1px)}.schema-grid,.card-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:1rem}.card-grid .invisra-card{text-align:center;padding:clamp(1.25rem,3vw,2rem)}.card-grid .invisra-card ul{display:inline-block;text-align:left;margin-left:0;padding-left:1.2rem}.card-grid .link-row{justify-content:center}.card-grid pre{text-align:left}.hero-card{padding:clamp(1.5rem,4vw,3rem);margin:2rem auto;text-align:center}.hero-card .lede{margin-left:auto;margin-right:auto}.hero-card .hero-actions,.hero-card .link-row{justify-content:center}.hero-actions,.link-row{display:flex;gap:.75rem;flex-wrap:wrap;align-items:center}.schema{text-align:center;padding:clamp(1.25rem,3vw,2rem)}.schema h3{margin-left:auto;margin-right:auto}.schema code,.invisra-code{overflow-wrap:anywhere}.muted{color:var(--invisra-muted,#94a3b8)}footer{padding:2rem 0;color:var(--invisra-muted,#94a3b8)}pre.invisra-code{white-space:pre-wrap;padding:1rem;border-radius:1rem}.theme-toggle{padding:.52rem .8rem}@media(max-width:760px){.site-nav{align-items:flex-start;flex-direction:column}.site-links{gap:.6rem}}
  </style>`;
}

function page(title, body) {
  return `<!doctype html>\n<html lang="en" data-theme="dark">\n<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <title>${escapeHtml(title)}</title>\n${brandHead()}\n  ${localStyles()}${analyticsSnippet()}\n</head>\n<body class="invisra-theme">\n${themeScript()}\n${siteHeader()}\n${body}\n</body>\n</html>\n`;
}

function validateSchemaIdVersion(file, schema) {
  if (!schema.$id) return;
  const match = schema.$id.match(new RegExp(`/${PROJECT_NAME}/([^/]+)/`));
  if (match && match[1] !== SCHEMA_VERSION) {
    throw new Error(`${file} has $id version ${match[1]}, but package.json version is ${SCHEMA_VERSION}`);
  }
}

const files = readdirSync(sourceDir)
  .filter((file) => file.endsWith('.schema.json'))
  .sort(schemaSort);
const schemas = files.map((file) => {
  const schema = readJson(path.join(sourceDir, file));
  validateSchemaIdVersion(file, schema);
  return {file, schema};
});

for (const destination of [PUBLIC_SCHEMA_DIR, PYTHON_SCHEMA_DIR, TYPESCRIPT_SCHEMA_DIR]) {
  const destinationDir = path.join(root, destination);
  mkdirSync(destinationDir, {recursive: true});

  for (const existing of readdirSync(destinationDir)) {
    const targetPath = path.join(destinationDir, existing);
    if (existing.endsWith('.schema.json') && statSync(targetPath).isFile()) rmSync(targetPath);
  }

  for (const {file} of schemas) copyFileSync(path.join(sourceDir, file), path.join(destinationDir, file));
}

writeGeneratedTypeScriptSchemas(path.join(root, TYPESCRIPT_GENERATED_SCHEMA_MODULE), schemas);

const publicProjectPath = path.join(root, PUBLIC_PROJECT_DIR);
const publicVersionPath = path.join(root, PUBLIC_SCHEMA_DIR);
mkdirSync(publicProjectPath, {recursive: true});
mkdirSync(publicVersionPath, {recursive: true});

const versions = readdirSync(publicProjectPath)
  .filter((entry) => /^\d+\.\d+\.\d+$/.test(entry) && statSync(path.join(publicProjectPath, entry)).isDirectory())
  .sort((a, b) => a.localeCompare(b, undefined, {numeric: true}));

writeJson(path.join(publicProjectPath, 'manifest.json'), {
  project: PROJECT_NAME,
  description: PROJECT_DESCRIPTION,
  versions: versions.map((version) => ({
    version,
    url: `/${PROJECT_NAME}/${version}/`,
    manifest: `/${PROJECT_NAME}/${version}/manifest.json`,
  })),
});

const schemaManifest = {
  project: PROJECT_NAME,
  version: SCHEMA_VERSION,
  schemas: schemas.map(({file, schema}) => ({
    filename: file,
    url: `/${PROJECT_NAME}/${SCHEMA_VERSION}/${file}`,
    id: schema.$id,
    title: schema.title,
    description: schema.description,
  })),
};
writeJson(path.join(publicVersionPath, 'manifest.json'), schemaManifest);

writeFileSync(path.join(root, 'public/index.html'), page('Invisra schemas | printspec', `<main class="invisra-shell">
  <section class="invisra-container invisra-card hero-card home-hero-card">
    <span class="invisra-badge">Developer schemas</span>
    <h1>Invisra Schemas</h1>
    <p class="invisra-text-muted lede">Public JSON Schemas for Invisra open-source projects, including printspec.</p>
    <div class="hero-actions">
      <a class="invisra-button invisra-button-primary" href="/${PROJECT_NAME}/">Open printspec schemas</a>
      <a class="invisra-button invisra-button-secondary" href="/${PROJECT_NAME}/validator/">Open validator</a>
    </div>
  </section>
  <section class="invisra-container card-grid" aria-label="Schema links">
    <article class="invisra-card"><h2>printspec</h2><p class="invisra-text-muted">JSON Schemas for practical parametric 3D-printable parts.</p><a href="/${PROJECT_NAME}/">View project</a></article>
    <article class="invisra-card"><h2>Validator</h2><p class="invisra-text-muted">Browser-only validation with bundled offline schemas.</p><a href="/${PROJECT_NAME}/validator/">Validate JSON</a></article>
    <article class="invisra-card"><h2>Invisra</h2><p class="invisra-text-muted">Open-source tooling and products for practical fabrication workflows.</p><a href="https://invisra.ai">Visit Invisra</a></article>
  </section>
</main>
<footer class="invisra-container">Schemas are provided for public reference. Validators should resolve bundled schemas offline where possible.</footer>`));

writeFileSync(path.join(publicProjectPath, 'index.html'), page('printspec schemas | Invisra', `<main class="invisra-shell">
  <section class="invisra-container invisra-card hero-card">
    <span class="invisra-badge">Open format</span>
    <h1>printspec</h1>
    <p class="invisra-text-muted lede">A practical JSON format for parametric 3D-printable parts.</p>
    <p>Schemas include browser-editor metadata where available so tools can build parameter forms from bundled schemas.</p>
    <div class="hero-actions"><a class="invisra-button invisra-button-primary" href="/${PROJECT_NAME}/validator/">Open validator</a><a class="invisra-button invisra-button-secondary" href="/${PROJECT_NAME}/${SCHEMA_VERSION}/">View schemas</a></div>
  </section>
  <section class="invisra-container card-grid">
    <article class="invisra-card"><h2>Versions</h2><ul>
${versions.map((version) => `      <li><a href="/${PROJECT_NAME}/${version}/">${version}</a></li>`).join('\n')}
    </ul></article>
    <article class="invisra-card"><h2>Usage example</h2><pre class="invisra-code"><code>{
  "printspecVersion": "${SCHEMA_VERSION}",
  "units": "mm",
  "part": { "type": "round_spacer" }
}</code></pre></article>
    <article class="invisra-card"><h2>References</h2><p class="link-row"><a href="/${PROJECT_NAME}/manifest.json">Project manifest</a><a href="${PROJECT_REPO_URL}">GitHub repository</a><a href="https://cad.invisra.ai">PartPilot</a></p></article>
  </section>
</main>`));

writeFileSync(path.join(publicVersionPath, 'index.html'), page(`printspec ${SCHEMA_VERSION} schemas | Invisra`, `<main class="invisra-shell">
  <section class="invisra-container invisra-card hero-card">
    <span class="invisra-badge">Version ${SCHEMA_VERSION}</span>
    <h1>printspec ${SCHEMA_VERSION} schemas</h1>
    <p class="invisra-text-muted">Versioned JSON Schemas for printspec ${SCHEMA_VERSION}.</p>
    <p class="link-row"><a class="invisra-button invisra-button-secondary" href="/${PROJECT_NAME}/">Back to printspec</a><a class="invisra-button invisra-button-primary" href="/${PROJECT_NAME}/validator/">Open validator</a><a class="invisra-button invisra-button-ghost" href="/${PROJECT_NAME}/${SCHEMA_VERSION}/manifest.json">Version manifest</a></p>
  </section>
  <section class="invisra-container">
    <h2>Schema files</h2>
    <div class="schema-grid">
${schemaManifest.schemas.map((schema) => `      <article class="invisra-card schema">
        <h3><a href="${escapeHtml(schema.filename)}">${escapeHtml(schema.filename)}</a></h3>
        ${schema.title ? `<p><strong>${escapeHtml(schema.title)}</strong></p>` : ''}
        ${schema.description ? `<p class="invisra-text-muted">${escapeHtml(schema.description)}</p>` : ''}
        ${schema.id ? `<p class="muted"><code class="invisra-code">${escapeHtml(schema.id)}</code></p>` : ''}
      </article>`).join('\n')}
    </div>
  </section>
</main>`));

writeFileSync(path.join(root, 'public/404.html'), page('Signal lost | Invisra', `<main class="invisra-shell">
  <section class="invisra-container invisra-card hero-card">
    <span class="invisra-badge">404</span>
    <h1>Signal lost.</h1>
    <p class="invisra-text-muted lede">The schema page or asset you requested does not exist, moved, or was never generated.</p>
    <div class="hero-actions"><a class="invisra-button invisra-button-primary" href="/${PROJECT_NAME}/">Open printspec home</a><a class="invisra-button invisra-button-secondary" href="/${PROJECT_NAME}/validator/">Open validator</a></div>
  </section>
</main>`));

console.log(`Synced ${files.length} schema files`);
console.log(`Public destination: ${PUBLIC_SCHEMA_DIR}`);
console.log(`Python package destination: ${PYTHON_SCHEMA_DIR}`);
console.log(`TypeScript package destination: ${TYPESCRIPT_SCHEMA_DIR}`);
console.log(`TypeScript generated schema module: ${TYPESCRIPT_GENERATED_SCHEMA_MODULE}`);
console.log(`Generated static schema indexes and manifests for ${PROJECT_NAME} ${SCHEMA_VERSION}`);
