import {
  copyFileSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import {
  root,
  PROJECT_NAME,
  PROJECT_DESCRIPTION,
  PROJECT_REPO_URL,
  SCHEMA_VERSION,
  PUBLIC_PROJECT_DIR,
  PUBLIC_SCHEMA_DIR,
} from "./lib/project-info.mjs";
import { escapeHtml, page } from "./lib/site-template.mjs";

const SOURCE_SCHEMA_DIR = "schemas";
const PYTHON_SCHEMA_DIR = "packages/python/printspec/schemas";
const TYPESCRIPT_SCHEMA_DIR = "packages/typescript/schemas";
const TYPESCRIPT_GENERATED_SCHEMA_MODULE = "packages/typescript/src/generated/schemas.generated.ts";
const sourceDir = path.join(root, SOURCE_SCHEMA_DIR);

function readJson(filePath) {
  return JSON.parse(readFileSync(filePath, "utf8"));
}

function writeJson(filePath, data) {
  writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`);
}

function writeGeneratedTypeScriptSchemas(filePath, schemaEntries) {
  const sorted = [...schemaEntries].sort((a, b) => a.file.localeCompare(b.file));
  const schemaLines = sorted
    .map(
      ({ file, schema }) =>
        `  ${JSON.stringify(file)}: ${JSON.stringify(schema, null, 2).replaceAll("\n", "\n  ")}`,
    )
    .join(",\n");
  const fileList = sorted.map(({ file }) => `  ${JSON.stringify(file)}`).join(",\n");
  const content = `// This file is generated by scripts/sync-schemas.mjs.\n// Do not edit manually.\n\nexport const bundledSchemas = {\n${schemaLines}\n} as const;\n\nexport const bundledSchemaFiles = [\n${fileList}\n] as const;\n`;
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, content);
}

function schemaSort(a, b) {
  if (a === "printspec.schema.json") return -1;
  if (b === "printspec.schema.json") return 1;
  return a.localeCompare(b);
}

function validateSchemaIdVersion(file, schema) {
  if (!schema.$id) return;
  const match = schema.$id.match(new RegExp(`/${PROJECT_NAME}/([^/]+)/`));
  if (match && match[1] !== SCHEMA_VERSION) {
    throw new Error(
      `${file} has $id version ${match[1]}, but package.json version is ${SCHEMA_VERSION}`,
    );
  }
}

const files = readdirSync(sourceDir)
  .filter((file) => file.endsWith(".schema.json"))
  .sort(schemaSort);
const schemas = files.map((file) => {
  const schema = readJson(path.join(sourceDir, file));
  validateSchemaIdVersion(file, schema);
  return { file, schema };
});

for (const destination of [PUBLIC_SCHEMA_DIR, PYTHON_SCHEMA_DIR, TYPESCRIPT_SCHEMA_DIR]) {
  const destinationDir = path.join(root, destination);
  mkdirSync(destinationDir, { recursive: true });

  for (const existing of readdirSync(destinationDir)) {
    const targetPath = path.join(destinationDir, existing);
    if (existing.endsWith(".schema.json") && statSync(targetPath).isFile()) rmSync(targetPath);
  }

  for (const { file } of schemas)
    copyFileSync(path.join(sourceDir, file), path.join(destinationDir, file));
}

writeGeneratedTypeScriptSchemas(path.join(root, TYPESCRIPT_GENERATED_SCHEMA_MODULE), schemas);

const publicProjectPath = path.join(root, PUBLIC_PROJECT_DIR);
const publicVersionPath = path.join(root, PUBLIC_SCHEMA_DIR);
mkdirSync(publicProjectPath, { recursive: true });
mkdirSync(publicVersionPath, { recursive: true });

const versions = readdirSync(publicProjectPath)
  .filter(
    (entry) =>
      /^\d+\.\d+\.\d+$/.test(entry) && statSync(path.join(publicProjectPath, entry)).isDirectory(),
  )
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

writeJson(path.join(publicProjectPath, "manifest.json"), {
  project: PROJECT_NAME,
  description: PROJECT_DESCRIPTION,
  versions: versions.map((version) => ({
    version,
    url: `/${PROJECT_NAME}/${version}/`,
    manifest: `/${PROJECT_NAME}/${version}/manifest.json`,
  })),
});

const schemaManifest = {
  project: PROJECT_NAME,
  version: SCHEMA_VERSION,
  schemas: schemas.map(({ file, schema }) => ({
    filename: file,
    url: `/${PROJECT_NAME}/${SCHEMA_VERSION}/${file}`,
    id: schema.$id,
    title: schema.title,
    description: schema.description,
  })),
};
writeJson(path.join(publicVersionPath, "manifest.json"), schemaManifest);

writeFileSync(
  path.join(root, "public/index.html"),
  page(
    "Invisra schemas | printspec",
    `<main class="invisra-shell">
  <section class="invisra-container invisra-card hero-card home-hero-card">
    <span class="invisra-badge">Developer schemas</span>
    <h1>Invisra Schemas</h1>
    <p class="invisra-text-muted lede">Public JSON Schemas for Invisra open-source projects, including printspec.</p>
    <div class="hero-actions">
      <a class="invisra-button invisra-button-primary" href="/${PROJECT_NAME}/">Open printspec schemas</a>
      <a class="invisra-button invisra-button-secondary" href="/${PROJECT_NAME}/validator/">Open validator</a>
    </div>
  </section>
  <section class="invisra-container card-grid" aria-label="Schema links">
    <article class="invisra-card"><h2>printspec</h2><p class="invisra-text-muted">JSON Schemas for practical parametric 3D-printable parts.</p><a href="/${PROJECT_NAME}/">View project</a></article>
    <article class="invisra-card"><h2>Validator</h2><p class="invisra-text-muted">Browser-only validation with bundled offline schemas.</p><a href="/${PROJECT_NAME}/validator/">Validate JSON</a></article>
    <article class="invisra-card"><h2>Invisra</h2><p class="invisra-text-muted">Open-source tooling and products for practical fabrication workflows.</p><a href="https://invisra.ai">Visit Invisra</a></article>
  </section>
</main>
<footer class="invisra-container">Schemas are provided for public reference. Validators should resolve bundled schemas offline where possible.</footer>`,
  ),
);

writeFileSync(
  path.join(publicProjectPath, "index.html"),
  page(
    "printspec schemas | Invisra",
    `<main class="invisra-shell">
  <section class="invisra-container invisra-card hero-card">
    <span class="invisra-badge">Open format</span>
    <h1>printspec</h1>
    <p class="invisra-text-muted lede">A practical JSON format for parametric 3D-printable parts.</p>
    <p>Schemas include browser-editor metadata where available so tools can build parameter forms from bundled schemas.</p>
    <div class="hero-actions"><a class="invisra-button invisra-button-primary" href="/${PROJECT_NAME}/${SCHEMA_VERSION}/docs/">Read the docs</a><a class="invisra-button invisra-button-secondary" href="/${PROJECT_NAME}/validator/">Open validator</a><a class="invisra-button invisra-button-secondary" href="/${PROJECT_NAME}/${SCHEMA_VERSION}/">View schemas</a></div>
  </section>
  <section class="invisra-container card-grid">
    <article class="invisra-card"><h2>Documentation</h2><p class="invisra-text-muted">Guides, generator notes, and API reference rendered from the repository's own docs.</p><p class="link-row"><a href="/${PROJECT_NAME}/${SCHEMA_VERSION}/docs/">Browse docs</a><a href="/llms.txt">llms.txt</a></p></article>
    <article class="invisra-card"><h2>Versions</h2><ul>
${versions.map((version) => `      <li><a href="/${PROJECT_NAME}/${version}/">${version}</a></li>`).join("\n")}
    </ul></article>
    <article class="invisra-card"><h2>Usage example</h2><pre class="invisra-code"><code>{
  "printspecVersion": "${SCHEMA_VERSION}",
  "units": "mm",
  "part": { "type": "round_spacer" }
}</code></pre></article>
    <article class="invisra-card"><h2>References</h2><p class="link-row"><a href="/${PROJECT_NAME}/manifest.json">Project manifest</a><a href="${PROJECT_REPO_URL}">GitHub repository</a><a href="https://cad.invisra.ai">PartPilot</a></p></article>
  </section>
</main>`,
  ),
);

writeFileSync(
  path.join(publicVersionPath, "index.html"),
  page(
    `printspec ${SCHEMA_VERSION} schemas | Invisra`,
    `<main class="invisra-shell">
  <section class="invisra-container invisra-card hero-card">
    <span class="invisra-badge">Version ${SCHEMA_VERSION}</span>
    <h1>printspec ${SCHEMA_VERSION} schemas</h1>
    <p class="invisra-text-muted">Versioned JSON Schemas for printspec ${SCHEMA_VERSION}.</p>
    <p class="link-row"><a class="invisra-button invisra-button-secondary" href="/${PROJECT_NAME}/">Back to printspec</a><a class="invisra-button invisra-button-primary" href="/${PROJECT_NAME}/${SCHEMA_VERSION}/docs/">Read the docs</a><a class="invisra-button invisra-button-secondary" href="/${PROJECT_NAME}/validator/">Open validator</a><a class="invisra-button invisra-button-ghost" href="/${PROJECT_NAME}/${SCHEMA_VERSION}/manifest.json">Version manifest</a></p>
  </section>
  <section class="invisra-container">
    <h2>Schema files</h2>
    <div class="schema-grid">
${schemaManifest.schemas
  .map(
    (schema) => `      <article class="invisra-card schema">
        <h3><a href="${escapeHtml(schema.filename)}">${escapeHtml(schema.filename)}</a></h3>
        ${schema.title ? `<p><strong>${escapeHtml(schema.title)}</strong></p>` : ""}
        ${schema.description ? `<p class="invisra-text-muted">${escapeHtml(schema.description)}</p>` : ""}
        ${schema.id ? `<p class="muted"><code class="invisra-code">${escapeHtml(schema.id)}</code></p>` : ""}
      </article>`,
  )
  .join("\n")}
    </div>
  </section>
</main>`,
  ),
);

writeFileSync(
  path.join(root, "public/404.html"),
  page(
    "Signal lost | Invisra",
    `<main class="invisra-shell">
  <section class="invisra-container invisra-card hero-card">
    <span class="invisra-badge">404</span>
    <h1>Signal lost.</h1>
    <p class="invisra-text-muted lede">The schema page or asset you requested does not exist, moved, or was never generated.</p>
    <div class="hero-actions"><a class="invisra-button invisra-button-primary" href="/${PROJECT_NAME}/">Open printspec home</a><a class="invisra-button invisra-button-secondary" href="/${PROJECT_NAME}/validator/">Open validator</a></div>
  </section>
</main>`,
  ),
);

console.log(`Synced ${files.length} schema files`);
console.log(`Public destination: ${PUBLIC_SCHEMA_DIR}`);
console.log(`Python package destination: ${PYTHON_SCHEMA_DIR}`);
console.log(`TypeScript package destination: ${TYPESCRIPT_SCHEMA_DIR}`);
console.log(`TypeScript generated schema module: ${TYPESCRIPT_GENERATED_SCHEMA_MODULE}`);
console.log(`Generated static schema indexes and manifests for ${PROJECT_NAME} ${SCHEMA_VERSION}`);
