import type {PrintSpec} from './types.js';
import type {ValidationResult} from './types.js';
import {normalizePrintSpec} from './normalize.js';
import {extractBom,bomToMarkdown,bomToCsv,bomToSupplierOrderList} from './bom.js';

export type BundleFile={path:string;content:string;mediaType:string};
export type BundleWarning={path?:string;message:string};
export type BundleResult={supported:boolean;files:BundleFile[];warnings:BundleWarning[];message?:string};
export type BundleOptions={includeOpenScad?:boolean;includeCadQuery?:boolean;includeBom?:boolean;includePartCad?:boolean;prettyJson?:boolean};
export type WriteBundleOptions={overwrite?:boolean};
type GenerateCad = (spec: PrintSpec) => {supported:boolean;code:string;message?:string;warnings?:string[]};
export type BundleDeps={validatePrintSpec:(spec: unknown)=>ValidationResult;generateOpenScad:GenerateCad;generateCadQuery:GenerateCad};
type RoleFile=BundleFile&{role:string};
const VERSION='0.1.0';
const jsonMedia='application/json';
function j(spec:any,pretty:boolean){return JSON.stringify(spec,null,pretty?2:0)+'\n';}
function add(files:RoleFile[],path:string,content:string,mediaType:string,role:string){files.push({path,content,mediaType,role});}
function warn(warnings:BundleWarning[],message:string,path?:string){warnings.push(path?{path,message}:{message});}
function safePartId(id:string){return id.replace(/[^A-Za-z0-9._-]/g,'-');}
function bomFiles(files:RoleFile[],base:string,bom:any[]){if(!bom.length)return; add(files,`${base}bom.md`,bomToMarkdown(bom)+'\n','text/markdown','bom-markdown'); add(files,`${base}bom.csv`,bomToCsv(bom)+'\n','text/csv','bom-csv'); add(files,`${base}supplier-order-list.txt`,bomToSupplierOrderList(bom)+'\n','text/plain','supplier-order-list');}
function cadForPart(deps:BundleDeps,spec:PrintSpec,base:string,files:RoleFile[],warnings:BundleWarning[],opts:Required<Pick<BundleOptions,'includeOpenScad'|'includeCadQuery'>>){if(opts.includeOpenScad){const g=deps.generateOpenScad(spec); if(g.supported){add(files,`${base}cad/model.scad`,g.code,'text/plain','openscad-source'); for(const m of g.warnings??[]) warn(warnings,m,`${base}cad/model.scad`);} else warn(warnings,g.message??'OpenSCAD generator unsupported',`${base}cad/model.scad`);} if(opts.includeCadQuery){const g=deps.generateCadQuery(spec); if(g.supported){add(files,`${base}cad/model.py`,g.code,'text/x-python','cadquery-source'); for(const m of g.warnings??[]) warn(warnings,m,`${base}cad/model.py`);} else warn(warnings,g.message??'CadQuery generator unsupported',`${base}cad/model.py`);}}
function readme(kind:'part'|'project',spec:any,files:RoleFile[],warnings:BundleWarning[],bomCount:number){const lines:string[]=[]; lines.push(`# ${kind==='project'?(spec.project?.label??'printspec project'):(spec.part?.label??'printspec part')}`,''); if(kind==='part') lines.push(`Part type: ${spec.part?.type??'unknown'}`); else {if(spec.project?.description) lines.push(spec.project.description,''); lines.push('## Parts',...(spec.project?.parts??[]).map((p:any)=>`- ${p.id}: ${p.label??p.id} (quantity ${p.quantity??1})`),'');} lines.push(`printspec version: ${spec.printspecVersion??VERSION}`,'','## Generated files',...files.map(f=>`- ${f.path} (${f.role})`),''); lines.push('## BOM',bomCount?`${bomCount} BOM item(s) included.`:'No hardware/BOM items were found.',''); lines.push('## Warnings',...(warnings.length?warnings.map(w=>`- ${w.path?`${w.path}: `:''}${w.message}`):['- None']),''); lines.push('Generated CAD source should be reviewed before manufacturing.'); return lines.join('\n')+'\n';}
function partcad(spec:any,files:RoleFile[]){const cq=files.filter(f=>f.role==='cadquery-source').sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0); const name=spec.project?.partcad?.packageName??'printspec-project'; const lines=['package:',`  name: ${name}`,`  version: ${spec.project?.partcad?.packageVersion??VERSION}`,'  description: Experimental compatibility stub generated from printspec.','','parts:']; for(const f of cq){const m=f.path.match(/^parts\/([^/]+)\//); lines.push(`  - name: ${m?.[1]??'model'}`,'    type: cadquery',`    path: ${f.path}`);} if(!cq.length) lines.push('  []'); return lines.join('\n')+'\n';}
function manifest(kind:'part'|'project',files:RoleFile[],warnings:BundleWarning[],spec:any){const entries=files.map(f=>({path:f.path,mediaType:f.mediaType,role:f.role})).sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0); entries.push({path:'bundle-manifest.json',mediaType:jsonMedia,role:'bundle-manifest'}); entries.sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0); return j({bundleVersion:VERSION,createdBy:'printspec',printspecVersion:spec.printspecVersion??VERSION,kind,files:entries,warnings},true);}
export function createBundleWithDeps(deps: BundleDeps, input:unknown,options:BundleOptions={}):BundleResult{const r=deps.validatePrintSpec(input as any); if(!r.valid)return {supported:false,files:[],warnings:[],message:`Validation failed: ${r.errors.slice(0,3).join('; ')}`}; const spec=normalizePrintSpec(input as PrintSpec); const opts={includeOpenScad:options.includeOpenScad!==false,includeCadQuery:options.includeCadQuery!==false,includeBom:options.includeBom!==false,includePartCad:options.includePartCad===true,prettyJson:options.prettyJson!==false}; const files:RoleFile[]=[]; const warnings:BundleWarning[]=[]; const kind=spec.project?'project':'part'; add(files,'printspec.json',j(spec,opts.prettyJson),jsonMedia,'source-spec'); if(kind==='part'){cadForPart(deps,spec,'',files,warnings,opts); if(opts.includeBom) bomFiles(files,'bom/',extractBom(spec));} else {for(const p of spec.project!.parts??[]){const id=safePartId(p.id); if(p.spec){const ps=normalizePrintSpec(p.spec); add(files,`parts/${id}/printspec.json`,j(ps,opts.prettyJson),jsonMedia,'part-source-spec'); cadForPart(deps,ps,`parts/${id}/`,files,warnings,opts);} else if(p.specPath) warn(warnings,`External specPath references are not bundled yet: ${p.specPath}`,`parts/${id}/printspec.json`);} if(opts.includeBom) bomFiles(files,'bom/',extractBom(spec)); if(opts.includePartCad) add(files,'partcad.yaml',partcad(spec,files),'text/yaml','partcad-stub');}
 const bomCount=extractBom(spec).length; add(files,'README.md',readme(kind,spec,files,warnings,bomCount),'text/markdown','readme'); add(files,'bundle-manifest.json',manifest(kind,files,warnings,spec),jsonMedia,'bundle-manifest'); files.sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0); return {supported:true,files:files.map(({role,...f})=>f),warnings};}
