import type {ValidationResult} from './types.js';
const types=['rounded_rectangular_plate','spacer_block','round_spacer','electronics_standoff','l_bracket','cable_comb','cable_clip','drill_guide','simple_box','simple_lid'];
const req:Record<string,string[]>={rounded_rectangular_plate:['length','width','thickness','cornerRadius'],spacer_block:['length','width','height'],round_spacer:['outerDiameter','height'],electronics_standoff:['outerDiameter','height','holeDiameter'],l_bracket:['legLengthA','legLengthB','width','thickness'],cable_comb:['length','width','thickness','slotCount','slotWidth','slotSpacing','slotDepth'],cable_clip:['baseLength','baseWidth','baseThickness','clipWallThickness'],drill_guide:['length','width','height','holeDiameter','holeCount','holeSpacing'],simple_box:['outerLength','outerWidth','outerHeight','wallThickness'],simple_lid:['length','width','thickness']};
function dim(v:any){return typeof v==='number'&&Number.isFinite(v)&&v>0&&v<=10000}
function hw(h:any,errors:string[]){if(!h.id||!h.kind||!Number.isInteger(h.quantity)||h.quantity<1) errors.push('invalid hardware item'); for(const r of h.supplierReferences??[]){if(!r.supplier||!r.partNumber) errors.push('invalid supplier reference'); if(r.url){try{new URL(r.url)}catch{errors.push('invalid supplier reference url')}}}}
export function validatePartFamilySpec(part:any):ValidationResult{const errors:string[]=[]; if(!part||!types.includes(part.type)) errors.push('unknown part type'); if(!part?.label) errors.push('missing label'); const p=part?.parameters; if(!p) errors.push('missing parameters'); for(const k of req[part?.type]??[]) if(!dim(p?.[k]) && !(part.type==='cable_clip' && (k==='clipInnerDiameter'||k==='clipOpeningWidth'))) errors.push(`invalid dimension ${k}`); if(part?.type==='cable_clip'&&!dim(p?.clipInnerDiameter)&&!dim(p?.clipOpeningWidth)) errors.push('clipInnerDiameter or clipOpeningWidth required'); for(const h of p?.holes??[]) if(!dim(h.diameter)||!(h.depth==='through'||dim(h.depth))) errors.push('invalid hole'); for(const h of part?.hardware??[]) hw(h,errors); return {valid:errors.length===0,errors};}
export function validateComposablePartSpec(part:any):ValidationResult{const errors:string[]=[]; if(part?.type!=='composable_part') errors.push('not composable_part'); if(!part?.label) errors.push('missing label'); if(!Array.isArray(part?.components)||part.components.length<1) errors.push('missing components'); for(const h of part?.hardware??[]) hw(h,errors); return {valid:errors.length===0,errors};}
export function validateProjectSpec(project:any):ValidationResult{const errors:string[]=[]; if(project?.type!=='project') errors.push('not project'); if(!project?.label) errors.push('missing label'); if(!Array.isArray(project?.parts)||project.parts.length<1) errors.push('missing parts'); for(const h of project?.hardware??[]) hw(h,errors); return {valid:errors.length===0,errors};}
export function validatePrintSpec(spec:any):ValidationResult{const errors:string[]=[]; if(spec?.printspecVersion!=='0.1.0') errors.push('invalid printspecVersion'); if(spec?.units!=='mm') errors.push('invalid units'); if((!!spec?.part)===(!!spec?.project)) errors.push('expected exactly one of part or project'); if(spec?.part){const r=spec.part.type==='composable_part'?validateComposablePartSpec(spec.part):validatePartFamilySpec(spec.part); errors.push(...r.errors)} if(spec?.project) errors.push(...validateProjectSpec(spec.project).errors); for(const h of spec?.hardware??[]) hw(h,errors); return {valid:errors.length===0,errors};}
