import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs'; import path from 'node:path'; import {spawnSync} from 'node:child_process';
import {validatePrintSpec,extractBom,bomToMarkdown,bomToCsv,bomToSupplierOrderList,generateOpenScad,generateCadQuery,normalizePrintSpec} from '../../packages/typescript/dist/index.js';
const root=path.resolve('../..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const norm=s=>s.replace(/\r\n/g,'\n').replace(/[ \t]+$/gm,'').trimEnd()+'\n';
const spec=read('examples/part-families/rounded-rectangular-plate.basic.json');
const project=read('examples/projects/simple-enclosure-project.json');
test('shared valid fixtures pass',()=>{for(const f of fs.readdirSync(path.join(root,'tests/fixtures/valid')).filter(f=>f.endsWith('.json'))){const r=validatePrintSpec(read('tests/fixtures/valid/'+f)); assert.equal(r.valid,true,`${f}: ${r.errors.join('; ')}`)}});
test('shared invalid fixtures fail',()=>{for(const f of fs.readdirSync(path.join(root,'tests/fixtures/invalid')).filter(f=>f.endsWith('.json'))){assert.equal(validatePrintSpec(read('tests/fixtures/invalid/'+f)).valid,false,f)}});
test('normalization does not mutate and defaults holes',()=>{const input=structuredClone(spec); const out=normalizePrintSpec(input); assert.deepEqual(input,spec); assert.equal(out.units,'mm');});
test('bom helpers work',()=>{const bom=extractBom(project); assert.equal(bom[0].quantity,4); assert.match(bomToMarkdown(bom),/lid_screws/); assert.match(bomToCsv(bom),/91292A112/); assert.match(bomToSupplierOrderList(bom),/mcmaster/);});
test('generators validate and emit safe deterministic code',()=>{assert.match(generateOpenScad(spec).code,/difference/); const cq=generateCadQuery(spec).code; assert.match(cq,/part =/); assert.doesNotMatch(cq,/export|subprocess|os\.|open\(/); const bad=structuredClone(spec); bad.part.parameters.cornerRadius=999; const res=generateOpenScad(bad); assert.equal(res.supported,false); assert.match(res.message,/Validation failed/);});
test('generator snapshots match fixtures',()=>{const items=[['rounded-rectangular-plate.basic','examples/part-families/rounded-rectangular-plate.basic.json'],['spacer-block.four-hole','examples/part-families/spacer-block.four-hole.json'],['round-spacer.basic','examples/part-families/round-spacer.basic.json'],['electronics-standoff.m3','examples/part-families/electronics-standoff.m3.json']]; for(const [name,file] of items){const s=read(file); assert.equal(norm(generateOpenScad(s).code),norm(fs.readFileSync(path.join(root,`tests/fixtures/generated/openscad/${name}.scad`),'utf8'))); assert.equal(norm(generateCadQuery(s).code),norm(fs.readFileSync(path.join(root,`tests/fixtures/generated/cadquery/${name}.py`),'utf8')));}});
test('round spacer warnings and standoff semantic validation',()=>{const s=read('examples/part-families/round-spacer.basic.json'); s.part.parameters.chamfer={distance:0.5}; assert.deepEqual(generateOpenScad(s).warnings,['chamfer requested but not implemented']); assert.equal(validatePrintSpec(read('tests/fixtures/invalid/electronics-standoff-base-too-small.json')).valid,false);});
test('typescript cli commands',()=>{const cli=path.join(root,'packages/typescript/dist/cli.js'); for(const args of [['validate','examples/part-families/rounded-rectangular-plate.basic.json'],['to-openscad','examples/part-families/round-spacer.basic.json'],['to-cadquery','examples/part-families/electronics-standoff.m3.json'],['bom','examples/projects/simple-enclosure-project.json','--format','markdown']]){const r=spawnSync('node',[cli,...args],{cwd:root,encoding:'utf8'}); assert.equal(r.status,0,`${args.join(' ')} ${r.stderr}`); assert.ok((r.stdout+r.stderr).length>0);} const bad=spawnSync('node',[cli,'validate','tests/fixtures/invalid/round-spacer-inner-too-large.json'],{cwd:root,encoding:'utf8'}); assert.equal(bad.status,1); assert.match(bad.stderr,/invalid/); const malformed=path.join(root,'tests/fixtures/invalid-json.tmp.json'); fs.writeFileSync(malformed,'{bad json'); try{const r=spawnSync('node',[cli,'validate',malformed],{cwd:root,encoding:'utf8'}); assert.equal(r.status,1); assert.match(r.stderr,/invalid-json\.tmp\.json/); assert.match(r.stderr,/parse error/);} finally{fs.rmSync(malformed,{force:true});}});

test('typescript cli version commands',()=>{const cli=path.join(root,'packages/typescript/dist/cli.js'); for(const args of [['--version'],['version']]){const r=spawnSync('node',[cli,...args],{cwd:root,encoding:'utf8'}); assert.equal(r.status,0,r.stderr); assert.match(r.stdout,new RegExp(`printspec ${read('packages/typescript/package.json').version.replaceAll('.', '\\.')}`));}});

test('typescript cli friendly user errors',()=>{const cli=path.join(root,'packages/typescript/dist/cli.js'); const help=spawnSync('node',[cli,'--help'],{cwd:root,encoding:'utf8'}); assert.equal(help.status,0,help.stderr); assert.match(help.stdout,/usage: printspec/); const badCommand=spawnSync('node',[cli,'wat'],{cwd:root,encoding:'utf8'}); assert.equal(badCommand.status,1); assert.match(badCommand.stderr,/unknown command wat/); assert.doesNotMatch(badCommand.stderr,/Error:|\n\s+at /); const missing=spawnSync('node',[cli,'validate','does-not-exist.json'],{cwd:root,encoding:'utf8'}); assert.equal(missing.status,1); assert.match(missing.stderr,/does-not-exist\.json/); assert.match(missing.stderr,/read error/); assert.doesNotMatch(missing.stderr,/Error:|\n\s+at /); const malformed=path.join(root,'tests/fixtures/invalid-json.tmp.json'); fs.writeFileSync(malformed,'{bad json'); try{const r=spawnSync('node',[cli,'validate',malformed],{cwd:root,encoding:'utf8'}); assert.equal(r.status,1); assert.match(r.stderr,/invalid-json\.tmp\.json/); assert.match(r.stderr,/parse error/); assert.doesNotMatch(r.stderr,/Error:|\n\s+at /);} finally{fs.rmSync(malformed,{force:true});}});

test('form metadata helpers and cli expose schema UI metadata',async()=>{const {getPartFamilyFormMetadata,listPartFamilies}=await import('../../packages/typescript/dist/index.js'); const families=listPartFamilies(); const schemaFiles=fs.readdirSync(path.join(root,'schemas')).filter(f=>f.endsWith('.schema.json')).map(f=>read('schemas/'+f)).filter(s=>s.properties?.type?.const&&s.properties?.parameters); assert.equal(families.length,schemaFiles.length); assert.ok(families.some(f=>f.type==='rounded_rectangular_plate'&&f.generatorSupported)); const rr=getPartFamilyFormMetadata('rounded_rectangular_plate'); assert.deepEqual(rr.fields.slice(0,4).map(f=>f.name),['length','width','thickness','cornerRadius']); assert.equal(rr.fields[0].unit,'mm'); assert.equal(rr.fields[0].control,'number'); assert.throws(()=>getPartFamilyFormMetadata('unknown_part'),/Unsupported/); const cli=path.join(root,'packages/typescript/dist/cli.js'); const meta=spawnSync('node',[cli,'form-metadata','spacer_block'],{cwd:root,encoding:'utf8'}); assert.equal(meta.status,0,meta.stderr); assert.equal(JSON.parse(meta.stdout).partType,'spacer_block'); const list=spawnSync('node',[cli,'list-part-families'],{cwd:root,encoding:'utf8'}); assert.equal(list.status,0,list.stderr); assert.ok(JSON.parse(list.stdout).some(f=>f.type==='spacer_block')); const bad=spawnSync('node',[cli,'form-metadata','missing'],{cwd:root,encoding:'utf8'}); assert.equal(bad.status,1);});

test('schema UI metadata quality',()=>{const rich=new Set(['rounded_rectangular_plate','spacer_block','round_spacer','electronics_standoff','simple_box','simple_lid']); for(const file of fs.readdirSync(path.join(root,'schemas')).filter(f=>f.endsWith('.schema.json'))){const schema=read('schemas/'+file); const partType=schema.properties?.type?.const; if(!partType||!schema.properties?.parameters) continue; assert.ok(schema.title, file); assert.ok(schema.description, file); const params=schema.properties.parameters; assert.ok(params.title, file); assert.ok(params.description, file); const props=params.properties; const names=new Set(Object.keys(props)); const ui=params['x-printspec-ui']; assert.ok(ui?.order, file); for(const name of ui.order) assert.ok(names.has(name), `${file} order ${name}`); for(const group of ui.groups??[]) for(const name of group.fields) assert.ok(names.has(name), `${file} group ${name}`); for(const req of params.required??[]) assert.ok(ui.order.includes(req)||(ui.groups??[]).some(g=>g.fields.includes(req)), `${file} required ${req}`); if(rich.has(partType)){for(const [name,field] of Object.entries(props)){assert.ok(field.title, `${file} ${name} title`); assert.ok(field.description, `${file} ${name} description`); assert.ok(field['x-printspec-control'], `${file} ${name} control`); if(field.type==='number') assert.ok(field['x-printspec-unit'], `${file} ${name} unit`);}} }});

test('bundle helpers create deterministic files and refuse traversal',async()=>{const {createBundle,writeBundleToDirectory}=await import('../../packages/typescript/dist/index.js'); const b=createBundle(spec,{includePartCad:true}); assert.equal(b.supported,true); const paths=b.files.map(f=>f.path); assert.deepEqual(paths,[...paths].sort()); assert.ok(paths.includes('printspec.json')); assert.ok(paths.includes('cad/model.scad')); assert.ok(paths.includes('cad/model.py')); assert.ok(paths.includes('README.md')); assert.ok(paths.includes('bundle-manifest.json')); assert.equal(JSON.parse(b.files.find(f=>f.path==='bundle-manifest.json').content).kind,'part'); assert.match(b.files.find(f=>f.path==='README.md').content,/Generated CAD source should be reviewed/); assert.throws(()=>writeBundleToDirectory({supported:true,files:[{path:'../evil',content:'x',mediaType:'text/plain'}],warnings:[]},'/tmp/printspec-bad',{overwrite:true}),/Unsafe/);});

test('bundle project and typescript cli write expected files',async()=>{const {createBundle}=await import('../../packages/typescript/dist/index.js'); const b=createBundle(project,{includePartCad:true}); const paths=b.files.map(f=>f.path); assert.ok(paths.includes('bom/bom.md')); assert.ok(paths.includes('partcad.yaml')); assert.ok(paths.includes('parts/base/printspec.json')); assert.ok(b.warnings.length>=2); const cli=path.join(root,'packages/typescript/dist/cli.js'); const out=path.join(root,'tests/fixtures/tmp-ts-bundle'); fs.rmSync(out,{recursive:true,force:true}); try{const r=spawnSync('node',[cli,'bundle','examples/part-families/rounded-rectangular-plate.basic.json','--output',out,'--overwrite'],{cwd:root,encoding:'utf8'}); assert.equal(r.status,0,r.stderr); assert.ok(fs.existsSync(path.join(out,'bundle-manifest.json'))); assert.ok(fs.existsSync(path.join(out,'cad/model.py'))); assert.match(r.stdout,/wrote \d+ files/);} finally{fs.rmSync(out,{recursive:true,force:true});}});
