def _holes(holes): return ''.join(f".pushPoints([({h['x']}, {h['y']})]).hole({h['diameter']})" for h in holes or [])
def generate_cadquery(spec):
    p=spec.get('part')
    if not p: return {'supported':False,'code':'','message':'Only part specs are supported.'}
    a=p['parameters']
    if p['type']=='rounded_rectangular_plate': return {'supported':True,'code':f"# Generated by printspec 0.1.0\nimport cadquery as cq\n\nlength = {a['length']}\nwidth = {a['width']}\nheight = {a['thickness']}\ncorner_radius = {a['cornerRadius']}\n\npart = cq.Workplane(\"XY\").rounded_rect(length, width, corner_radius).extrude(height){_holes(a.get('holes'))}\n"}
    if p['type']=='spacer_block': return {'supported':True,'code':f"# Generated by printspec 0.1.0\nimport cadquery as cq\n\nlength = {a['length']}\nwidth = {a['width']}\nheight = {a['height']}\n\npart = cq.Workplane(\"XY\").box(length, width, height, centered=(True, True, False)){_holes(a.get('holes'))}\n"}
    return {'supported':False,'code':'','message':f"Unsupported part family: {p['type']}"}
