from ..validate import validate_printspec
HEADER='# Generated by printspec 0.1.0\n# Review generated CAD before manufacturing.\nimport cadquery as cq\n\n'
def _warnings(a):
    w=[]
    if a.get('chamfer') is not None: w.append('chamfer requested but not implemented')
    if a.get('fillet') is not None: w.append('fillet requested but not implemented')
    return w
def _holes(holes): return '\n'.join(f"part = part.faces(\">Z\").workplane().pushPoints([({h['x']}, {h['y']})]).hole({h['diameter']})" for h in holes or [])
def generate_cadquery(spec):
    r=validate_printspec(spec)
    if not r['valid']: return {'supported':False,'code':'','message':'Validation failed: '+'; '.join(r['errors'][:3]),'warnings':[]}
    p=spec.get('part')
    if not p: return {'supported':False,'code':'','message':'Only part specs are supported.','warnings':[]}
    a=p['parameters']
    if p['type']=='rounded_rectangular_plate': return {'supported':True,'warnings':[],'code':f"{HEADER}length = {a['length']}\nwidth = {a['width']}\nheight = {a['thickness']}\ncorner_radius = {a['cornerRadius']}\n\npart = cq.Workplane(\"XY\").rounded_rect(length, width, corner_radius).extrude(height)\n{_holes(a.get('holes'))}\n"}
    if p['type']=='spacer_block': return {'supported':True,'warnings':[],'code':f"{HEADER}length = {a['length']}\nwidth = {a['width']}\nheight = {a['height']}\n\npart = cq.Workplane(\"XY\").box(length, width, height, centered=(True, True, False))\n{_holes(a.get('holes'))}\n"}
    if p['type']=='round_spacer': return {'supported':True,'warnings':_warnings(a),'code':f"{HEADER}outer_diameter = {a['outerDiameter']}\nheight = {a['height']}"+(f"\ninner_diameter = {a['innerDiameter']}" if a.get('innerDiameter') is not None else '')+"\n\npart = cq.Workplane(\"XY\").circle(outer_diameter / 2).extrude(height)"+("\npart = part.faces(\">Z\").workplane().hole(inner_diameter)" if a.get('innerDiameter') is not None else '')+"\n"}
    if p['type']=='electronics_standoff':
        has_base=a.get('baseDiameter') is not None and a.get('baseHeight') is not None
        body=("base = cq.Workplane(\"XY\").circle(base_diameter / 2).extrude(base_height)\nstandoff = cq.Workplane(\"XY\").workplane(offset=base_height).circle(outer_diameter / 2).extrude(height)\npart = base.union(standoff)" if has_base else "part = cq.Workplane(\"XY\").circle(outer_diameter / 2).extrude(height)")
        return {'supported':True,'warnings':[],'code':f"{HEADER}outer_diameter = {a['outerDiameter']}\nheight = {a['height']}\nhole_diameter = {a['holeDiameter']}"+(f"\nbase_diameter = {a['baseDiameter']}\nbase_height = {a['baseHeight']}" if has_base else '')+f"\n\n{body}\npart = part.faces(\">Z\").workplane().hole(hole_diameter)\n"}
    return {'supported':False,'code':'','message':f"Unsupported part family: {p['type']}",'warnings':[]}
