import json

from ..validate import validate_printspec

HEADER = "// Generated by printspec 0.2.0\n// Review generated CAD before manufacturing.\n\n"


def _or(v, d):
    return d if v is None else v


def _warnings(a, corner_radius=True, chamfer=True):
    """Several part families' schemas include chamfer/fillet/cornerRadius
    (and, for l_bracket, rib) as optional finishing requests that most
    generators don't implement. Rather than silently drop them, report a
    warning so callers know the request was ignored. Pass corner_radius=False
    for the one family (rounded_rectangular_plate) that actually implements
    cornerRadius, and chamfer=False for a family/case that actually builds the
    requested chamfer.
    """
    w = []
    if chamfer and a.get("chamfer") is not None:
        w.append("chamfer requested but not implemented")
    if a.get("fillet") is not None:
        w.append("fillet requested but not implemented")
    if (a.get("rib") or {}).get("enabled"):
        w.append("rib requested but not implemented")
    if corner_radius and a.get("cornerRadius") is not None:
        w.append("cornerRadius requested but not implemented")
    return w


def _whole_part_chamfer(a):
    """Return the chamfer distance to apply to the whole part, or None.

    Only whole-part chamfers (no ``target``) are built; a targeted chamfer
    stays an unimplemented-warning until per-edge targeting is supported.
    """
    c = a.get("chamfer")
    if c is not None and c.get("target") is None:
        return c.get("distance")
    return None


def _holes(holes):
    return "\n".join(
        f"  translate([{h['x']}, {h['y']}, -0.1]) cylinder(h = height + 0.2, d = {h['diameter']}, $fn = 48);"
        for h in holes or []
    )


def _l_bracket_cuts(holes, slots, thickness, width):
    """l_bracket has two legs on different axes (leg A flat, thin along Z; leg
    B standing up, thin along X), so unlike the single-axis families above,
    its holes/slots must be cut along whichever axis the Hole/Slot specifies.
    axis "z" cuts through leg A at (x, y); axis "x" cuts through leg B,
    reusing x as the position along leg B's length and y as the lateral
    position (matching leg A's convention). axis "y" isn't supported;
    matching entries are skipped and reported as a warning instead of
    silently misplaced.
    """
    lines = []
    unsupported_axis = False

    def through_depth(axis):
        return width if axis == "y" else thickness

    for h in holes or []:
        axis = h.get("axis") or "z"
        if axis not in ("z", "x"):
            unsupported_axis = True
            continue
        depth = h["depth"]
        depth = through_depth(axis) if depth in ("through", None) else depth
        if axis == "z":
            lines.append(
                f"  translate([{h['x']}, {h['y']}, -0.1]) cylinder(h = {depth} + 0.2, d = {h['diameter']}, $fn = 32);"
            )
        else:
            lines.append(
                f"  translate([-0.1, {h['y']}, {h['x']}]) rotate([0, 90, 0]) cylinder(h = {depth} + 0.2, d = {h['diameter']}, $fn = 32);"
            )
    for s in slots or []:
        axis = s.get("axis")
        if axis not in ("z", "x"):
            unsupported_axis = True
            continue
        depth = s["depth"]
        depth = through_depth(axis) if depth in ("through", None) else depth
        if axis == "z":
            lines.append(
                f"  translate([{s['x']} - {s['length']} / 2, {s['y']} - {s['width']} / 2, -0.1]) cube([{s['length']}, {s['width']}, {depth} + 0.2]);"
            )
        else:
            lines.append(
                f"  translate([-0.1, {s['y']} - {s['width']} / 2, {s['x']} - {s['length']} / 2]) cube([{depth} + 0.2, {s['width']}, {s['length']}]);"
            )
    return "\n".join(lines), unsupported_axis


def generate_openscad(spec):
    r = validate_printspec(spec)
    if not r["valid"]:
        return {
            "supported": False,
            "code": "",
            "message": "Validation failed: " + "; ".join(r["errors"][:3]),
            "warnings": [],
        }
    p = spec.get("part")
    if not p:
        return {
            "supported": False,
            "code": "",
            "message": "Only part specs are supported.",
            "warnings": [],
        }
    a = p["parameters"]
    if p["type"] == "rounded_rectangular_plate":
        return {
            "supported": True,
            "warnings": _warnings(a, corner_radius=False),
            "code": f"{HEADER}length = {a['length']};\nwidth = {a['width']};\nheight = {a['thickness']};\ncorner_radius = {a['cornerRadius']};\n\nmodule rounded_plate() {{\n  hull() {{\n    for (x = [-length/2 + corner_radius, length/2 - corner_radius])\n      for (y = [-width/2 + corner_radius, width/2 - corner_radius])\n        translate([x, y, 0]) cylinder(h = height, r = corner_radius, $fn = 32);\n  }}\n}}\n\ndifference() {{\n  rounded_plate();\n{_holes(a.get('holes'))}\n}}\n",
        }
    if p["type"] == "spacer_block":
        c = _whole_part_chamfer(a)
        if c is not None:
            body = (
                f"chamfer = {c};\n\nmodule chamfered_box() {{\n  hull() {{\n"
                "    linear_extrude(0.01) square([length - 2*chamfer, width - 2*chamfer], center = true);\n"
                "    translate([0, 0, chamfer]) linear_extrude(height - 2*chamfer) square([length, width], center = true);\n"
                "    translate([0, 0, height - 0.01]) linear_extrude(0.01) square([length - 2*chamfer, width - 2*chamfer], center = true);\n"
                f"  }}\n}}\n\ndifference() {{\n  chamfered_box();\n{_holes(a.get('holes'))}\n}}\n"
            )
        else:
            body = f"\ndifference() {{\n  translate([-length/2, -width/2, 0]) cube([length, width, height]);\n{_holes(a.get('holes'))}\n}}\n"
        return {
            "supported": True,
            "warnings": _warnings(a, chamfer=c is None),
            "code": f"{HEADER}length = {a['length']};\nwidth = {a['width']};\nheight = {a['height']};\n{body}",
        }
    if p["type"] == "round_spacer":
        c = _whole_part_chamfer(a)
        inner = (
            "\n  translate([0, 0, -0.1]) cylinder(h = height + 0.2, d = inner_diameter, $fn = 64);"
            if a.get("innerDiameter") is not None
            else ""
        )
        outer_solid = (
            "rotate_extrude($fn = 64) polygon([[0, 0], [outer_diameter/2 - chamfer, 0], [outer_diameter/2, chamfer], [outer_diameter/2, height - chamfer], [outer_diameter/2 - chamfer, height], [0, height]])"
            if c is not None
            else "cylinder(h = height, d = outer_diameter, $fn = 64)"
        )
        return {
            "supported": True,
            "warnings": _warnings(a, chamfer=c is None),
            "code": f"{HEADER}outer_diameter = {a['outerDiameter']};\nheight = {a['height']};"
            + (f"\nchamfer = {c};" if c is not None else "")
            + (
                f"\ninner_diameter = {a['innerDiameter']};"
                if a.get("innerDiameter") is not None
                else ""
            )
            + f"\n\ndifference() {{\n  {outer_solid};{inner}\n}}\n",
        }
    if p["type"] == "electronics_standoff":
        has_base = a.get("baseDiameter") is not None and a.get("baseHeight") is not None
        body = (
            "union() {\n    cylinder(h = base_height, d = base_diameter, $fn = 64);\n    translate([0, 0, base_height]) cylinder(h = height, d = outer_diameter, $fn = 64);\n  }"
            if has_base
            else "cylinder(h = height, d = outer_diameter, $fn = 64);"
        )
        return {
            "supported": True,
            "warnings": _warnings(a),
            "code": f"{HEADER}outer_diameter = {a['outerDiameter']};\nheight = {a['height']};\nhole_diameter = {a['holeDiameter']};"
            + (
                f"\nbase_diameter = {a['baseDiameter']};\nbase_height = {a['baseHeight']};"
                if has_base
                else ""
            )
            + f"\n\ndifference() {{\n  {body}\n  translate([0, 0, -0.1]) cylinder(h = {'base_height + height' if has_base else 'height'} + 0.2, d = hole_diameter, $fn = 64);\n}}\n",
        }
    if p["type"] == "cable_comb":
        count = float(_or(a.get("slotCount"), 6))
        sw = float(_or(a.get("slotWidth"), 4))
        tw = float(_or(a.get("toothWidth"), (float(_or(a.get("slotSpacing"), 6)) - sw or 2)))
        sd = float(_or(a.get("slotDepth"), 8))
        th = float(_or(a.get("baseThickness"), _or(a.get("thickness"), 3)))
        length = float(_or(a.get("length"), count * sw + (count + 1) * tw))
        width = float(_or(a.get("width"), sd + tw))
        cuts = ""
        for i in range(int(count)):
            cuts += f"  translate([{-length / 2 + tw + i * (sw + tw)}, {width / 2 - sd}, -0.1]) cube([{sw}, {sd + 0.2}, {th + 0.2}]);\n"
        hd = float(_or(a.get("mountHoleDiameter"), 0))
        if hd > 0:
            sp = float(_or(a.get("mountHoleSpacing"), 40))
            cuts += f"  translate([{-sp / 2}, 0, -0.1]) cylinder(h = {th + 0.2}, d = {hd}, $fn = 32);\n  translate([{sp / 2}, 0, -0.1]) cylinder(h = {th + 0.2}, d = {hd}, $fn = 32);\n"
        return {
            "supported": True,
            "warnings": _warnings(a),
            "code": f"{HEADER}// Part family: cable_comb\n// Parameters: {json.dumps(a)}\n\ndifference() {{\n  translate([{-length / 2}, {-width / 2}, 0]) cube([{length}, {width}, {th}]);\n{cuts}}}\n",
        }
    if p["type"] == "cable_clip":
        base_length = _or(a.get("baseLength"), 28)
        width = _or(a.get("width"), _or(a.get("baseWidth"), 12))
        thickness = _or(a.get("thickness"), _or(a.get("baseThickness"), 3))
        cable_diameter = _or(a.get("cableDiameter"), _or(a.get("clipInnerDiameter"), 6))
        clearance = _or(a.get("clearance"), 0.5)
        mount_holes = "\n".join(
            f"  translate([{h['x']}, {h['y']}, -0.1]) cylinder(h = thickness + 0.2, d = {h['diameter']}, $fn = 32);"
            for h in a.get("mountingHoles") or []
        )
        return {
            "supported": True,
            "warnings": ["Cable arch is approximated as a rectangular bridge.", *_warnings(a)],
            "code": f"{HEADER}// Part family: cable_clip\n// Parameters: {json.dumps(a)}\n\nbase_length = {base_length};\nwidth = {width};\nthickness = {thickness};\ncable_diameter = {cable_diameter};\ndifference() {{\n  union() {{\n    translate([-base_length/2, -width/2, 0]) cube([base_length, width, thickness]);\n    translate([-base_length*0.325, -width/2, thickness + cable_diameter/2]) cube([base_length*0.65, width, thickness]);\n  }}\n  translate([0, -width/2 - 0.1, thickness + cable_diameter/2]) rotate([-90,0,0]) cylinder(h = width + 0.2, d = cable_diameter + {clearance}, $fn = 48);\n{mount_holes}\n}}\n",
        }
    if p["type"] == "wall_mount_bracket":
        return {
            "supported": True,
            "warnings": _warnings(a),
            "code": f"{HEADER}// Part family: wall_mount_bracket\n// Parameters: {json.dumps(a)}\n\nwidth = {a['width']}; height = {a['height']}; thickness = {a['thickness']}; tab_depth = {a['tabDepth']}; screw_hole_diameter = {a['screwHoleDiameter']}; screw_hole_spacing = {a['screwHoleSpacing']};\ndifference() {{\n  union() {{\n    translate([-width/2, -thickness/2, 0]) cube([width, thickness, height]);\n    translate([-width/2, 0, 0]) cube([width, tab_depth, thickness]);\n  }}\n  for (z = [height/2 - screw_hole_spacing/2, height/2 + screw_hole_spacing/2]) translate([0, -thickness/2 - 0.1, z]) rotate([-90,0,0]) cylinder(h = thickness + 0.2, d = screw_hole_diameter, $fn = 32);\n}}\n",
        }
    if p["type"] == "l_bracket":
        cuts, unsupported_axis = _l_bracket_cuts(
            a.get("holes"), a.get("slots"), a["thickness"], a["width"]
        )
        w = ["Light-duty/non-structural bracket; review before use.", *_warnings(a)]
        if unsupported_axis:
            w.append("hole/slot with axis 'y' is not implemented for l_bracket")
        return {
            "supported": True,
            "warnings": w,
            "code": f"{HEADER}// Part family: l_bracket\n// Parameters: {json.dumps(a)}\n\nleg_a = {a['legLengthA']}; leg_b = {a['legLengthB']}; width = {a['width']}; thickness = {a['thickness']};\ndifference() {{\n  union() {{\n    translate([0, -width/2, 0]) cube([leg_a, width, thickness]);\n    translate([0, -width/2, 0]) cube([thickness, width, leg_b]);\n  }}\n{cuts}\n}}\n",
        }
    if p["type"] == "drawer_divider":
        notch_count = _or(a.get("notchCount"), 0)
        return {
            "supported": True,
            "warnings": _warnings(a),
            "code": f"{HEADER}// Part family: drawer_divider\n// Parameters: {json.dumps(a)}\n\nlength = {a['length']}; height = {a['height']}; thickness = {a['thickness']}; notch_count = {notch_count}; notch_width = {a.get('notchWidth')}; notch_depth = {a.get('notchDepth')};\ndifference() {{\n  translate([-length/2, -thickness/2, 0]) cube([length, thickness, height]);\n  for (i = [1:notch_count]) translate([-length/2 + i * length / (notch_count + 1) - notch_width/2, -thickness/2 - 0.1, height - notch_depth]) cube([notch_width, thickness + 0.2, notch_depth + 0.1]);\n}}\n",
        }
    if p["type"] == "project_enclosure_tray":
        mount_hole_diameter = _or(a.get("mountHoleDiameter"), 3)
        mount_hole_inset = _or(a.get("mountHoleInset"), 8)
        return {
            "supported": True,
            "warnings": _warnings(a),
            "code": f"{HEADER}// Part family: project_enclosure_tray\n// Parameters: {json.dumps(a)}\n\nouter_width = {a['outerWidth']}; outer_depth = {a['outerDepth']}; wall_height = {a['wallHeight']}; wall_thickness = {a['wallThickness']}; floor_thickness = {a['floorThickness']}; mount_hole_diameter = {mount_hole_diameter}; mount_hole_inset = {mount_hole_inset};\ndifference() {{\n  union() {{\n    translate([-outer_width/2, -outer_depth/2, 0]) cube([outer_width, outer_depth, floor_thickness]);\n    translate([-outer_width/2, -outer_depth/2, floor_thickness]) cube([outer_width, wall_thickness, wall_height]);\n    translate([-outer_width/2, outer_depth/2 - wall_thickness, floor_thickness]) cube([outer_width, wall_thickness, wall_height]);\n    translate([-outer_width/2, -outer_depth/2, floor_thickness]) cube([wall_thickness, outer_depth, wall_height]);\n    translate([outer_width/2 - wall_thickness, -outer_depth/2, floor_thickness]) cube([wall_thickness, outer_depth, wall_height]);\n  }}\n  for (x = [-outer_width/2 + mount_hole_inset, outer_width/2 - mount_hole_inset]) for (y = [-outer_depth/2 + mount_hole_inset, outer_depth/2 - mount_hole_inset]) translate([x,y,-0.1]) cylinder(h = floor_thickness + 0.2, d = mount_hole_diameter, $fn = 32);\n}}\n",
        }
    return {
        "supported": False,
        "code": "",
        "message": f"Unsupported part family: {p['type']}",
        "warnings": [],
    }
