from ..validate import validate_printspec
HEADER='// Generated by printspec 0.1.0\n// Review generated CAD before manufacturing.\n'
def _warnings(a):
    w=[]
    if a.get('chamfer') is not None: w.append('chamfer requested but not implemented')
    if a.get('fillet') is not None: w.append('fillet requested but not implemented')
    return w
def _holes(holes): return '\n'.join(f"  translate([{h['x']}, {h['y']}, -0.1]) cylinder(h = height + 0.2, d = {h['diameter']}, $fn = 48);" for h in holes or [])
def generate_openscad(spec):
    r=validate_printspec(spec)
    if not r['valid']: return {'supported':False,'code':'','message':'Validation failed: '+'; '.join(r['errors'][:3]),'warnings':[]}
    p=spec.get('part')
    if not p: return {'supported':False,'code':'','message':'Only part specs are supported.','warnings':[]}
    a=p['parameters']
    if p['type']=='rounded_rectangular_plate': return {'supported':True,'warnings':[],'code':f"{HEADER}length = {a['length']};\nwidth = {a['width']};\nheight = {a['thickness']};\ncorner_radius = {a['cornerRadius']};\n\nmodule rounded_plate() {{\n  hull() {{\n    for (x = [-length/2 + corner_radius, length/2 - corner_radius])\n      for (y = [-width/2 + corner_radius, width/2 - corner_radius])\n        translate([x, y, 0]) cylinder(h = height, r = corner_radius, $fn = 32);\n  }}\n}}\n\ndifference() {{\n  rounded_plate();\n{_holes(a.get('holes'))}\n}}\n"}
    if p['type']=='spacer_block': return {'supported':True,'warnings':[],'code':f"{HEADER}length = {a['length']};\nwidth = {a['width']};\nheight = {a['height']};\n\ndifference() {{\n  translate([-length/2, -width/2, 0]) cube([length, width, height]);\n{_holes(a.get('holes'))}\n}}\n"}
    if p['type']=='round_spacer':
        inner=f"\n  translate([0, 0, -0.1]) cylinder(h = height + 0.2, d = inner_diameter, $fn = 64);" if a.get('innerDiameter') is not None else ''
        return {'supported':True,'warnings':_warnings(a),'code':f"{HEADER}outer_diameter = {a['outerDiameter']};\nheight = {a['height']};"+(f"\ninner_diameter = {a['innerDiameter']};" if a.get('innerDiameter') is not None else '')+f"\n\ndifference() {{\n  cylinder(h = height, d = outer_diameter, $fn = 64);{inner}\n}}\n"}
    if p['type']=='electronics_standoff':
        has_base=a.get('baseDiameter') is not None and a.get('baseHeight') is not None
        body=("union() {\n    cylinder(h = base_height, d = base_diameter, $fn = 64);\n    translate([0, 0, base_height]) cylinder(h = height, d = outer_diameter, $fn = 64);\n  }" if has_base else "cylinder(h = height, d = outer_diameter, $fn = 64);")
        return {'supported':True,'warnings':[],'code':f"{HEADER}outer_diameter = {a['outerDiameter']};\nheight = {a['height']};\nhole_diameter = {a['holeDiameter']};"+(f"\nbase_diameter = {a['baseDiameter']};\nbase_height = {a['baseHeight']};" if has_base else '')+f"\n\ndifference() {{\n  {body}\n  translate([0, 0, -0.1]) cylinder(h = {'base_height + height' if has_base else 'height'} + 0.2, d = hole_diameter, $fn = 64);\n}}\n"}
    return {'supported':False,'code':'','message':f"Unsupported part family: {p['type']}",'warnings':[]}
